### ISSUE TITLE
ViT_Large

### ISSUE THREAD

**Issue by FDInSky** [exiawsh/StreamPETR#102]
https://github.com/exiawsh/StreamPETR/blob/main/docs/ViT_Large.md 
this config can get the best performance like nuscenes benchmark?

**Comment by yingfei1016** [comment]
Yes，if you use the deformable version the performance will even higher.

**Comment by FDInSky** [comment]
do you try to add depth to get better result ?
https://github.com/FiveLu/stream3dppe

**Comment by yingfei1016** [comment]
I not try it, but it's a solid work, you can make a try. My primary focus is no longer upon BEV perception.
