### ISSUE TITLE
Concern about the temoporal propogation

### ISSUE THREAD

**Issue by Jacky-gsq** [exiawsh/StreamPETR#104]
Hi, I have recently conducted some experiments on temporal propagation and have some new confusion. 
Additionally, note the following description "Analysis of Moving Objects " in Section 5 Expriment in the paper: 

> The detection performance of moving objects still lags behind that of static objects to a large margin even with temporal modeling.

I wonder if there is a quantitative evaluation for the  performance of detection on static and dynamic objects or its data distribution. Furthermore, is the reason for the poor performance of moving object due to inaccurate velosity prediction?

Could you please explain it or just have a deeper discussion？

Thanks a lot!

**Comment by exiawsh** [comment]
We followed bevstereo to evaluate the performance of moving objects. I can show you the code. But it may not the best way. Just for fair comparison with previous methods.

**Comment by Jacky-gsq** [comment]
Thanks a lot!
