### ISSUE TITLE
About the compatibility of mmdet3d version

### ISSUE THREAD

**Issue by sakuraie** [exiawsh/StreamPETR#105]
Dear authors, sorry for bothering you. I'd like to ask if I use StreamPETR in mmdet3d whose version is < 1.0 (such as 0.17.2), will there be an impact on the performance of the detector? If so, can I revise some code to avoid the problem by like [this link](https://github.com/dvlab-research/UVTR/blob/main/projects/mmdet3d_plugin/core/bbox/util.py#L13)?

**Comment by YoushaaMurhij** [comment]
@exiawsh, Are you planning to support newer mmdet3d versions (> 1.1.0)?

**Comment by exiawsh** [comment]
@YoushaaMurhij I do have a similar plan. But it could take a month or two. I'm catching up on eccv.
