### ISSUE TITLE
ViT-large implementation problems.

### ISSUE THREAD

**Issue by synsin0** [exiawsh/StreamPETR#106]
I encountered several problem regarding backbone design according to your ViT_large instructions. May you take a look at these problems?
1. EVA/EVA-02's rope can not handle image size height!=width. Is the possible solution to generate freqs_sin, freqs_cos during the training process?
2. sim_fpn issue: scale_factors=[4,2,1,0.5,0.25] since EVA provides scale=[4,2,1,0.5], how is the 0.25 branch, maybe with 2 nn.Maxpool module? I'd like to ask with your sim_fpn, should the stride be [4,8,16,32,64] for RepDETR3D?
3. how to add the arg global_window_size=20 in detectron2's ViT codes.
Thanks a lot if you may give instructions. Currently I cannot reproduce comparable results with ViT-large(3-4 points less than in ViT-large.md).

**Comment by yingfei1016** [comment]
1、After the third problem solved, the rope will also be solved. 

2、Everything is OK.  You can use 2 nn.Maxpool.

3、Similar to 16x16 local attention, define a global_window_size param, send it to the place where global attention is needed.

**Comment by synsin0** [comment]
I corrected the problems above and encounter a problem with output strides. If YoloXHead inputs image features with stride=[4,8,16,32,64], the error occurs after one train step: File "/home/syn/miniconda3/envs/pcdet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`.  If the input stride is [8, 16, 32, 64], the training process goes successfully. Which stride is suitable for the settings of YoloXHead and SparseHead ?

**Comment by yingfei1016** [comment]
It's not a difficult thing, you'd better solve by yourself.
