### ISSUE TITLE
Can't find units of measurement for the results.json

### ISSUE THREAD

**Issue by odd2022** [exiawsh/StreamPETR#109]
Hello,

Sorry, it might be written somewhere but I can't find what are the units of measurement and the frame used in the results.json file.

I would also like to know to what corresponds each coordinate of 'translation' and 'rotation' please.

Have a nice day

**Comment by exiawsh** [comment]
@odd2022 Hi! Would you please provide a detailed explanation? I didn't get the point.

**Comment by odd2022** [comment]
My goal is to use the results of the object detection obtained by the model. These, if i am correct are stored in a file 'results.json'

Here is an example: 

 "3e8750f331d7499e9b5123e9eb70f2e2": [
            {
                "sample_token": "3e8750f331d7499e9b5123e9eb70f2e2",
                "translation": [
                    581.4793027404043,
                    1661.4289504580324,
                    1.343706165508077
                ],
                "size": [
                    1.8709721565246582,
                    4.534564018249512,
                    1.5506099462509155
                ],
                "rotation": [
                    0.2351789077520048,
                    0.029540215421324064,
                    -0.011615377549967523,
                    0.9714336518907538
                ],
                "velocity": [
                    -6.855158526701055,
                    3.6822105431603513
                ],
                "detection_name": "car",
                "detection_score": 0.8986459970474243,
                "attribute_name": "vehicle.moving"
            },
            
 I would like to know which unit of measurement is used to provide these results, is this the meters unit for translation or size ?
   
I would also like to know in which frame are computed the coordinates... Is this the ego frame ? Is there somewhere I can find all of these informations ? 

Is the rotation given in quaternions coordinates ? 

I hope this is more clear !

**Comment by exiawsh** [comment]
The translation is the xyz location in the global coordinate. The rotation is given in quaternions in the global coordinate.

**Comment by exiawsh** [comment]
You can refer to line622 https://raw.githubusercontent.com/open-mmlab/mmdetection3d/1.0/mmdet3d/datasets/nuscenes_dataset.py

**Comment by odd2022** [comment]
Ok thank you ! I found what I wanted
