### ISSUE TITLE
can not find the dist_params in config  file

### ISSUE THREAD

**Issue by lianshushu** [exiawsh/StreamPETR#11]
/StreamPETR-main/tools/train.py", line 165, in main
    init_dist(args.launcher, **cfg.dist_params)
/python3.9/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'dist_params'

**Comment by exiawsh** [comment]
Need more information. I need to reproduce the error.
Which config did you use？ And the running command?

**Comment by lianshushu** [comment]
I use the command：
tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 8 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/

**Comment by exiawsh** [comment]
What is your GPU devices? How many GPUs did you use？

**Comment by exiawsh** [comment]
Try to add this to the config:
dist_params = dict(backend='nccl')

**Comment by exiawsh** [comment]
You should check the version of your mmdet3d, it may have some problems. This config is inherited from mmdet3d.

https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/configs/_base_/default_runtime.py#L13

**Comment by lianshushu** [comment]
> What is your GPU devices? How many GPUs did you use？

I use A100, four GPU

**Comment by exiawsh** [comment]
> > What is your GPU devices? How many GPUs did you use？
> 
> I use A100, four GPU

As I mentioned above, this config is inherited from mmdet3d.
https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/configs/_base_/default_runtime.py#L13
please check the version of mmdet3d.

**Comment by exiawsh** [comment]
You also should mofied the commad:
from
tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 8 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/
to
tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 4 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/

**Comment by lianshushu** [comment]
> > > What is your GPU devices? How many GPUs did you use？
> > 
> > 
> > I use A100, four GPU
> 
> As I mentioned above, this config is inherited from mmdet3d. https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/configs/_base_/default_runtime.py#L13 please check the version of mmdet3d.



> You should check the version of your mmdet3d, it may have some problems. This config is inherited from mmdet3d.
> 
> https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/configs/_base_/default_runtime.py#L13

oh, I see,thank you so much!
