### ISSUE TITLE
Question about boxes projection on each image

### ISSUE THREAD

**Issue by YoushaaMurhij** [exiawsh/StreamPETR#110]
Thanks for open-sourcing this great work!
I am trying to understand the procedure of projecting the 3d bboxes on the images. Could you please correct me If I am wrong?
- The output 3D boxes are in global frame so we convert the boxes format (N, 9) to corners format (N, 8, 2). 
- After that we tranform these corners to ego vehicle frame (using 'ego_pose' or 'ego_pose_inv' - I am not sure which one to use).
- Next, we transform 3d corners to 2d corners in image frame(pixels) on the each image using the 'lidar2img' data of each camera (or its inverse - I'm not sure, too).
Is that correct? Could you please tell me which matrix to use in each step?

Thanks

**Comment by exiawsh** [comment]
@YoushaaMurhij I think you can refer to this. https://github.com/exiawsh/StreamPETR/blob/11ed0dc19b1852500ab3c7d2e6a0df237f6e28b8/tools/visual_nuscenes.py#L328

**Comment by YoushaaMurhij** [comment]
@exiawsh, Thanks, I will check that. I wonder if it is possible to run the model only using front camera from nuscnes dataset by changling the config file. Any suggestions?

**Comment by exiawsh** [comment]
@YoushaaMurhij It will not work if you just change the config file. You should modify the dataset.

**Comment by YoushaaMurhij** [comment]
I did not get it. Could you please refer to the part of code for that?

**Comment by YoushaaMurhij** [comment]
Also, in case of feeding one image in the dataloader this error happens:
```bash
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/detectors/petr3d.py", line 217, in forward
    return self.forward_test(**data)
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/detectors/petr3d.py", line 284, in forward_test
    return self.simple_test(img_metas[0], **data)
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/detectors/petr3d.py", line 313, in simple_test
    bbox_pts = self.simple_test_pts(
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/detectors/petr3d.py", line 299, in simple_test_pts
    outs = self.pts_bbox_head(location, img_metas, topk_indexes, **data)
  File "/home/anaconda3/envs/streampetr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 593, in forward
    pos_embed, cone = self.position_embeding(data, memory_center, topk_indexes, img_metas)
  File "/home/workspace/StreamPETR/./projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 396, in position_embeding
    memory_centers = memory_centers.detach().view(B, LEN, 1, 2)
RuntimeError: shape '[1, 4224, 1, 2]' is invalid for input of size 1408
```

**Comment by YoushaaMurhij** [comment]
I just solved it removing the other data from the dataloader. Thanks for you mentions. But still confused about the projection issue.

**Comment by YoushaaMurhij** [comment]
@exiawsh, The ouput boxes directly after inference are in ego vehicle pose but they are moved to global frame in results.json for evaluation purposes, is that correct?
In this case, I only need the 'intrinsics' and 'extrinsics' matrix to project the boxes on the corresponding images. 
Could you please comment on that?
Thanks

**Comment by exiawsh** [comment]
@YoushaaMurhij Sorry for the late response. You can refer to this code. https://github.com/exiawsh/storage/releases/download/v1.0/vis.py

**Comment by YoushaaMurhij** [comment]
Thanks a lot. Not at all. You response rapidly and your references helped alot.
