### ISSUE TITLE
ResNet-50 Single key frame training results

### ISSUE THREAD

**Issue by Eashwar93** [exiawsh/StreamPETR#111]
Hi, 

Thanks for open-sourcing your nice work. I have a question regarding ResNet-50 single keyframe training results. The result that you posted with the log [here](https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_r50_flash_704_bs2_seq_24e.log) is really good for the small image resolution you use. I just wanted to clarify that it was only trained with only a single keyframe since the `queue_length` was set to `1`. In that case, I was thinking that your results should be the same as Focal-PETR but instead you gained 4.4% mAP as shown in the table at the bottom of the [page](https://github.com/exiawsh/StreamPETR/blob/main/docs/training_inference.md). Could you explain to me why you have gained the 4.4%, it would be super interesting to know :)

**Comment by exiawsh** [comment]
@Eashwar93 Hi, it was trained by multi-frames setting. Not a single keyframe.

**Comment by Eashwar93** [comment]
@exiawsh thanks for the quick response. Could I know how many frames did you use and which config parameter to look into to identify the number of keyframes used in the training? I was thinking that it was queue_length 😅

**Comment by exiawsh** [comment]
@Eashwar93 This issue will be helpful.

**Comment by Eashwar93** [comment]
@exiawsh I am not able to understand your response. Did you want to point me to another issue where I could get my question answered? In that case there in no link in your previous response. Or do you in general think that this issue needs to be resolved with some re-factoring?

**Comment by exiawsh** [comment]
@Eashwar93 I'm sorry for the mistake. https://github.com/exiawsh/StreamPETR/issues/24#issuecomment-1573128569

**Comment by Eashwar93** [comment]
@exiawsh Thank you so much for the clarifications
