### ISSUE TITLE
the function of the tgt

### ISSUE THREAD

**Issue by RouDanCongJii** [exiawsh/StreamPETR#112]
i wonder the function of the tgt which is init defined as a zero-like matrix and can this model use lidar info

**Comment by exiawsh** [comment]
I'm sorry. Would you please provide more details about your question?

**Comment by RouDanCongJii** [comment]
https://github.com/exiawsh/StreamPETR/blob/11ed0dc19b1852500ab3c7d2e6a0df237f6e28b8/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L600
 
`tgt = self.ego_pose_memory(tgt, rec_ego_motion)`](https://github.com/exiawsh/StreamPETR/blob/11ed0dc19b1852500ab3c7d2e6a0df237f6e28b8/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L431)

the meaning of tgt in stream petr

**Comment by exiawsh** [comment]
@RouDanCongJii tgt is context embedding of object queries, which are zero initialized in the first decoder layer.
