### ISSUE TITLE
Result for tracking

### ISSUE THREAD

**Issue by goahence** [exiawsh/StreamPETR#118]
Hello, I am a senior student. Since my undergraduate degree is related to multi-target tracking, can you provide **the json file** of your detection results? I want to use this for my tracking algorithm. Thank you very much for your help

**Comment by exiawsh** [comment]
@goahence Hi, which sub set do you want? Val or test set?

**Comment by goahence** [comment]
Maybe both could be better. In addition, could you please offer the detector config information so that it's easier for me to annotate it in my work? Thanks very much

**Comment by exiawsh** [comment]
@goahence I can only provide you results on val set. Because I have no access on the model file on test set. Would you please give me your email?

**Comment by goahence** [comment]
2420934652@qq.com, thx
