### ISSUE TITLE
Questions about tgt

### ISSUE THREAD

**Issue by NaomiEX** [exiawsh/StreamPETR#119]
Hi, great work, it's very interesting! I was wondering why

1. [tgt is set as a zero tensor?](https://github.com/exiawsh/StreamPETR/blob/f04692185931f88e3dd3b7450247cafd24539ad8/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L600). Seeing as this is eventually used as the query in the decoder I'm interested in why it was fixed as zero instead of something learnable?
2. Also I'm quite confused about the purpose of [this code](https://github.com/exiawsh/StreamPETR/blob/f04692185931f88e3dd3b7450247cafd24539ad8/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L431).

**Comment by exiawsh** [comment]
@NaomiEX Sorry for late response.
1. The tgt is context embedding of object queries, which are zero initialized in the first decoder layer. I tried the learnable embedding before, it had no improvement.
2. You can ignore it, I just adopt the same operation as the memory embedding. If you don't do this operation, the performance will be the same.

**Comment by NaomiEX** [comment]
thank you so much for your quick response!
