### ISSUE TITLE
RepDETR3D有用到连续帧吗？

### ISSUE THREAD

**Issue by BadNaive** [exiawsh/StreamPETR#120]
大神您好！
请问RepDETR3D有用到连续帧（序列）吗？我看到config文件中有seq_split_num=2以及seq_mode=True，但是好像模型代码里面没有连续帧相关的计算内容，还望大神抽空指点！
谢谢！

**Comment by exiawsh** [comment]
@BadNaive 使用了，连续帧的数据处理请参考dataset和sampler.

**Comment by BadNaive** [comment]
> @BadNaive 使用了，连续帧的数据处理请参考dataset和sampler.

找到了！感谢大佬百忙之中抽空指点！
