### ISSUE TITLE
about the shape of norm operation?

### ISSUE THREAD

**Issue by czy341181** [exiawsh/StreamPETR#122]
hi, thanks for your great work! 

I have a question about the shape of norm operation.

https://github.com/exiawsh/StreamPETR/blob/16f2275c7335684223c0a51e130bd4a2bf15d8ad/projects/mmdet3d_plugin/models/utils/petr_transformer.py#L728

the input of norm layer is [num_query, bs, embed_dim]. 
Is it a bug?

**Comment by czy341181** [comment]
I found that different shapes can lead to differences in the calculation results . 
Do you know why?

**Comment by exiawsh** [comment]
@czy341181 Thanks for your attention. What do you think is the right operation?

**Comment by exiawsh** [comment]
Do you mean it should be changed to:
elif layer == 'norm':
    query = query.transpose(0, 1)
    query = self.norms[norm_index](query)
    query = query.transpose(0, 1)
    norm_index += 1
The results is normal.
We use batch_first = True in multihead attention by default.

**Comment by czy341181** [comment]
Should the results calculated by the two be equal?

**Comment by exiawsh** [comment]
The mAP result is the same as the original implementation.

**Comment by czy341181** [comment]
What I mean is, in this operation, the different shape of input  can lead to  different results

**Comment by exiawsh** [comment]
You change the order of dimension. It's normal the result will change. Because the dim order is not the same. But layer norm only operates in the last dim, just the order changes, the numerical value is the same.

**Comment by exiawsh** [comment]
@czy341181 If you still have questions, feel free to reopen the issue.
