### ISSUE TITLE
Always topk_proposals   == num_propagted ?

### ISSUE THREAD

**Issue by Slonna** [exiawsh/StreamPETR#124]
Hi, I noticed that the value of num_propagated is always set to be same with topk_proposals  in all the config file.
Is this deliberate or random?
And I think that in this way, the memory_bank will not store any output of previous frame because all of them are propagated.
The memory_bank is more like a hidden state?
Do I understand correctly?

**Comment by exiawsh** [comment]
The num_propaged can be different with topk_proposals. You can modify the hyper parameters.
The memory bank save 4 frames query features. In our setting, only the queris from the last frame are propagated. The others use global attentiom to interative with current queries.

**Comment by Slonna** [comment]
I re-read the code and  understand it now. I misunderstood it before. Thanks for your reply.
