### ISSUE TITLE
why do not align the reference_points in temporal_alignment ?

### ISSUE THREAD

**Issue by Slonna** [exiawsh/StreamPETR#125]
Hi, It seems that it just aligns the query and query_pos using the velocity , doesn't align the reference_points ?
In my view, I think the reference_points are like the box position .  
It seems that transform it just considering the ego motion in the pre_update_memory function. 
Not like the query_pos consider the velocity also.
[code](https://github.com/exiawsh/StreamPETR/blob/16f2275c7335684223c0a51e130bd4a2bf15d8ad/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L603C48-L603C48)
```python
       tgt, query_pos, reference_points, temp_memory, temp_pos, rec_ego_pose = self.temporal_alignment(query_pos, tgt, reference_points)
```

**Comment by Slonna** [comment]
In my view, I think the reference_points are like the box position .

**Comment by exiawsh** [comment]
Hi, the referce_points are processed here: https://github.com/exiawsh/StreamPETR/blob/16f2275c7335684223c0a51e130bd4a2bf15d8ad/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L332
