### ISSUE TITLE
why ? assert len(np.bincount(new_flags)) == len(np.bincount(self.flag)) * self.seq_split_num

### ISSUE THREAD

**Issue by hjfenghj** [exiawsh/StreamPETR#127]
What is the meaning of this judgment statement? If self.seq_ Split_ If num=2, then if there is only one frame of data in a certain sequence, an interrupt will occur

![image](https://github.com/exiawsh/StreamPETR/assets/72334253/4a694633-e047-43c9-8d62-d0531deec035)

code position:projects/mmdet3d_plugin/datasets/nuscenes_dataset.py -> def _set_sequence_group_flag()

**Comment by exiawsh** [comment]
Actually you can comment this line, which will not affect the results.

**Comment by hjfenghj** [comment]
thank you for your reply
