### ISSUE TITLE
为什么memory_len 大小设置为1024,如果按缓存4帧的query，这里len不应该是1024*4吗？

### ISSUE THREAD

**Issue by Xiang95** [exiawsh/StreamPETR#129]
![企业微信截图_17019158575998](https://github.com/exiawsh/StreamPETR/assets/27827152/d71617a2-f289-4ce1-a49a-dead291c033b)

**Comment by exiawsh** [comment]
@Xiang95 topk_proposals是每帧缓存的memory长度*4为1024

**Comment by Xiang95** [comment]
明白了，感谢大佬
