### ISSUE TITLE
is it posible to use KITTI dataset?

### ISSUE THREAD

**Issue by RashoAli** [exiawsh/StreamPETR#131]
is it posible to use KITTI dataset?

**Comment by exiawsh** [comment]
I think you can try our temporal modeling with monodetr.

**Comment by RashoAli** [comment]
Thanks for the replay,
i wanted to use the stereo setup from KITTI for tracking.
will that be posible?

**Comment by exiawsh** [comment]
I think it can work. But you should modify the dataset.
