### ISSUE TITLE
LayerNorm in cls_branch

### ISSUE THREAD

**Issue by zhengye1995** [exiawsh/StreamPETR#133]
I find there are LayerNorm in cls_branch which is not very efficient in development. I want to know if removing it will have a significant impact on performance. (PS: I found that it was from DETR3D). Thanks!

**Comment by exiawsh** [comment]
Thanks for your attention! I think it may will not have a significant impant on the results. You can simplify it.

**Comment by zhengye1995** [comment]
Got it, thanks!
