### ISSUE TITLE
How to set training frames in an annotated keyframe at 10Hz?

### ISSUE THREAD

**Issue by Tony-Hou** [exiawsh/StreamPETR#135]
When to use stream video method to train model,  How to set training frames in an annotated keyframe at 10Hz?
<img width="527" alt="image" src="https://github.com/exiawsh/StreamPETR/assets/26059901/c63b8b1e-5778-4247-8279-81d399d2a0bd">

**Comment by exiawsh** [comment]
@Tony-Hou These models are trained on argoverse v2 dataset. You may refer to Far3D. https://github.com/megvii-research/Far3D

**Comment by Tony-Hou** [comment]
> @Tony-Hou These models are trained on argoverse v2 dataset. You may refer to Far3D. https://github.com/megvii-research/Far3D
I compared  followed two configuration files and found no  essential difference. Where is  Far3d  setup training frames at 10Hz? 
**Left is**: StreamPETR//mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py  **Right is**: Far3D/projects/mmdet3d_plugin/datasets/argoverse2_dataset.py

<img width="1646" alt="企业微信截图_eda4cc05-ced9-470b-9151-ecd44194fe8f" src="https://github.com/exiawsh/StreamPETR/assets/26059901/9cd672e1-7753-4b3c-a990-91500ccaf978">

![企业微信截图_b0747182-608c-43f8-b72d-7c3507fc2122_副本](https://github.com/exiawsh/StreamPETR/assets/26059901/89840f39-c310-4c49-b089-f8d216b49e55)

<img width="1664" alt="image" src="https://github.com/exiawsh/StreamPETR/assets/26059901/ea7e81d3-6038-4d2b-aa5e-c4422facb53d">

**Comment by exiawsh** [comment]
The argo2 dataset was annotated in 10hz. You can refer to line 27 in https://raw.githubusercontent.com/megvii-research/Far3D/main/projects/mmdet3d_plugin/datasets/argoverse2_dataset_t.py. It can be splited into different time interval.
