### ISSUE TITLE
What is the  meaning of different configuration file?

### ISSUE THREAD

**Issue by Tony-Hou** [exiawsh/StreamPETR#136]
- seq indicates  streaming  video train method?
- What is the meaning of 428q?
- What is the meaning of nui?

![image](https://github.com/exiawsh/StreamPETR/assets/26059901/22efdb91-bd0f-42dd-9018-3faf326e9679)

**Comment by exiawsh** [comment]
@Tony-Hou 428q means 428 object queries. In the default setting, object queries are set to 900. nui means nuImage backbone pretrain.
