### ISSUE TITLE
特征可视化

### ISSUE THREAD

**Issue by konglinhua** [exiawsh/StreamPETR#138]
请问有尝试过对backbone或者FPN的特征可视化吗，我尝试用EigenCAM可视化FPN后效果很差，但是NDS是54.2，用的config是repdetr3d_r50_704_bs2_seq_90e.py,把vov变成了r50
![0_2](https://github.com/exiawsh/StreamPETR/assets/33696039/86fd3217-e01b-4b54-a4b6-b5eab6f92920)
![0_3](https://github.com/exiawsh/StreamPETR/assets/33696039/488fef79-8e5a-4bad-8463-08946e53c0dd)
![0_4](https://github.com/exiawsh/StreamPETR/assets/33696039/8455b302-23a9-4e65-a793-dc5e9d7cb750)
![0_5](https://github.com/exiawsh/StreamPETR/assets/33696039/fb2e3104-f679-4120-9fdd-d34cd0b92373)
![0_0](https://github.com/exiawsh/StreamPETR/assets/33696039/3853f15b-d19d-4b94-88be-921b3b8a1908)
![0_1](https://github.com/exiawsh/StreamPETR/assets/33696039/9c9afdd0-93ca-4ddb-8922-2d1391dcf4cf)

**Comment by exiawsh** [comment]
@konglinhua 抱歉，目前还真没做过这块的可视化。我们可视化一般看的是decoder中每个object query投影过来的attention可视化。我想是不是可视化之前需要对可视化做个norm，有些数值比较大，导致可视化效果不好？

**Comment by konglinhua** [comment]
嗯嗯，这个是对图像和Heatmap归一化之后按照权重相加的结果，我还尝试了下用torch中提供的R50对这个图像可视化看下，结果看着合理一些，就一直很纳闷。还想请教一下，你们可视化的attention是针对下边函数中的weight吗？
![vis_nuscenes](https://github.com/exiawsh/StreamPETR/assets/33696039/c08e4178-e3e3-4a60-aa1e-53d1d61bceee)

```python
    def forward(self, instance_feature, query_pos,feat_flatten, reference_points, spatial_flatten, level_start_index, pc_range, lidar2img_mat, img_metas):
        bs, num_anchor = reference_points.shape[:2]
        reference_points = get_global_pos(reference_points, pc_range)
        key_points = reference_points.unsqueeze(-2) + self.learnable_fc(instance_feature).reshape(bs, num_anchor, -1, 3)

        weights = self._get_weights(instance_feature, query_pos, lidar2img_mat)

        features = self.feature_sampling(feat_flatten, spatial_flatten, level_start_index, key_points, weights, lidar2img_mat, img_metas)

        output = self.output_proj(features)
        output = self.drop(output) + instance_feature
        return output
‘’‘

**Comment by exiawsh** [comment]
@konglinhua deformable attention版本用的是这个weights。
