### ISSUE TITLE
what are the point_cloud_range in the config files

### ISSUE THREAD

**Issue by RashoAli** [exiawsh/StreamPETR#139]
Does the model use only images for tracking? If so, why is the `point_cloud_range`  parameter present in all the config files? dose is use the pointcloud from the Lidar?

Additionally, I can't locate where the depth for the 3D positional encoding is computed. Is it determined as a preprocessing step and subsequently integrated into the database creation phase?

**Comment by RashoAli** [comment]
@exiawsh Thanks for the fast reply,
1. what do you mean with 'regression range (xyz) of our model'?
2. can you pleas tell me where the code is for calculating the 3D PE?
3. if i want to use 3DPPE which parameter should i use?

**Comment by exiawsh** [comment]
@RashoAli 
1. Our model only detects objects within the pointcloud range.
2. 
3.https://github.com/FiveLu/stream3dppe

**Comment by RashoAli** [comment]
@exiawsh 
how can the model deside if an object is to far or to close if just uses the images?

**Comment by exiawsh** [comment]
@RashoAli It's a learnable behavior. e.g. overfitting the height of the ground/size of the vehicle.

**Comment by RashoAli** [comment]
thanks very much for the fast answers.
i am currently working on understanding this part of the model so i belive i will have more question about it in the next day or tow :)
