### ISSUE TITLE
How would I perform inference on a single jpg image?

### ISSUE THREAD

**Issue by praveenkrishna0512** [exiawsh/StreamPETR#14]
Dear StreamPETR team,

I have managed to reproduce your results under your paper using the `stream_petr_vov_flash_800_bs2_seq_24e.py` config file and latest checkpoint. I am wondering how I may modify `test.py` to load my own image and run inference on the model. Thank you!

**Comment by praveenkrishna0512** [comment]
I just want to do inference on one single image

**Comment by exiawsh** [comment]
Hi,
I think modify the code based on https://github.com/exiawsh/StreamPETR/blob/74bf34a720d91e29550391e90a2f24c5f13ab1b0/tools/benchmark.py#L96 is much easier than test.py.
You should change the **data.
Besides, I am a little pessimistic about the results on your own dataset because of the domain adaption issue.

**Comment by praveenkrishna0512** [comment]
Alright thank you! I will try that out. May I clarify what your concern is regarding the domain adaption issue?

We were thinking about that as well. The key differences we identified when comparing our use case vs self-driving is the following:

1. The view of our cameras overlap significantly
2. Our cameras are not moving (so I believe there is no need for `ego_pose`)

**Comment by exiawsh** [comment]
I think you can finetune the model on your own dataset. Because the **number of tokens for keys and values** in cross attention (6 (num_cams) * 1000 in our case) may be quite different from yours.

**Comment by praveenkrishna0512** [comment]
Yeap! We wanted to do a preliminary testing before doing training, just to see whether our data can be fed into the model and get some rough sense.

Do you suggest fine-tuning the model based on the pre-trained FCOS3D or your checkpoint?

**Comment by exiawsh** [comment]
> Yeap! We wanted to do a preliminary testing before doing training, just to see whether our data can be fed into the model and get some rough sense.
> 
> Do you suggest fine-tuning the model based on the pre-trained FCOS3D or your checkpoint?

Sorry, I am not very sure the about using which pre-trained weights (Intuitively, our checkpoint may be better?).

**Comment by praveenkrishna0512** [comment]
No worries! I am interested to try and use this model for my company's use case. I believe that I am getting stuck in the implementation details and would appreciate any help on that front :)

I do have some questions regarding the suitability of the model for our use case, and I also hope to better understand the model from you.

Would you be free for a quick call this week? I would very much appreciate it, thank you!

**Comment by exiawsh** [comment]
Feel free to reopen this issue or contact us at wangshihao02@megvii.com

**Comment by zheng-hr** [comment]
> I just want to do inference on one single image

Hi, I want to do inference on one single image as well but I'm encountering some difficulties getting it to run properly with my current modifications. I wonder if you could share how you approached modifying your code for this task. That will help me a lot, thank you!
