### ISSUE TITLE
How to test the inference speed to get the result in paper ?

### ISSUE THREAD

**Issue by dop0** [exiawsh/StreamPETR#141]
Sorry to bother you. I try to test speed by check `task/s` field from the outputs of following command:
```
tools/dist_test.sh projects/configs/test_speed/stream_petr_r50_704_bs2_seq_428q_nui_speed_test.py \
work_dirs/stream_petr_r50_flash_704_bs2_seq_428q_nui_60e.pth 1 --eval bbox
```
I only get 5fps with a 3090, but SOLOFusion can achieve 10fps in same machine. I want to know if this is the correct way to measure speed, and what are the reasons for the slower speed, is it due to hardware?

**Comment by exiawsh** [comment]
@dop0 Try this command. I think 5fps with a 3090 is abnormal. 
python tools/benchmark.py projects/configs/test_speed/stream_petr_r50_704_bs2_seq_428q_nui_speed_test.py

**Comment by dop0** [comment]
@exiawsh Thanks for your quick reply.  It can basically achieve the expected result.
