### ISSUE TITLE
regarding Motion-aware Layer Normalization

### ISSUE THREAD

**Issue by RashoAli** [exiawsh/StreamPETR#143]
Dear author,

Thank you for the great work and the very interesting approach. I am trying to understand the "Motion-aware Layer Normalization" part of the model:
1. Why does the model calculate 'beta' and 'gamma'? What do these parameters represent? And why add and multiply these parameters with the queries afterward?

2. For pose, time, and velocity: Are these parameters extracted from the detected queries, or are they part of the ground truth (GT)?

**Comment by exiawsh** [comment]
@RashoAli beta and gamma are learnable parameters that implicitly containing the motion information.
pose and time are record in the nusc dataset. velocity is from the prediction results.
