### ISSUE TITLE
aboutQuery DeNoising

### ISSUE THREAD

**Issue by wofeifeileni** [exiawsh/StreamPETR#148]
Hi, I am very interested in query denoising in StreamPETR. I have a few simple questions to ask:
1. How to understand query denoising? Does this idea come from DN-DETR?
2. Which codes in the project can I find relevant information in? What do the following parameters represent?
![image](https://github.com/exiawsh/StreamPETR/assets/126314381/1d352f64-f421-45d5-a13b-7d97b05ab48a)

**Comment by exiawsh** [comment]
Hi,
1. We refer to DN-detr to implement query denosing.
2. In StreamPETR Head line 451

**Comment by wofeifeileni** [comment]
Thank you, I have found it and I will learn it.
