### ISSUE TITLE
focalhead initialization

### ISSUE THREAD

**Issue by Alexanderisgod** [exiawsh/StreamPETR#15]
when i train the model, it throws an error, as follows:
File "/home/xxxx/anaconda3/lib/python3.6/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: FocalHead: Can't instantiate abstract class FocalHead with abstract methods get_bboxes

**Comment by exiawsh** [comment]
Hi,
Would you please provide you mmcv and mmdetection3d version?

**Comment by Alexanderisgod** [comment]
> 
Sorry, i reinstall the mmcv, mmdet et.al. And it works well now.
