### ISSUE TITLE
关于使用Focal-PETR实现图像特征的前景、背景排序

### ISSUE THREAD

**Issue by PG-Wang** [exiawsh/StreamPETR#150]
您好，我在follow您的工作时，对于代码中为和要使用topk_indexes对memory进行排序产生了疑惑。
(1)请问在cross attention前，使用topk_indexes对memory进行排序，这对于petr中query聚焦于前景障碍物起到什么作用呢？请问这个过程是否与自注意中的attn_mask有相关性？
(2)在我的理解中topk_indexes是img_roi_head中提取的当前帧信息中，有类别的前景障碍物与背景障碍物的排序索引，排名越靠前表示越为前景特征。attn_mask是为了更好的初始化query的值，使query中的位置信息能更加关注于由真值噪声的初始化信息。请问这样理解有问题吗？

添麻烦了，非常期望您的回答，上面这几个点思考了很长一段时间但一直没有结论。

**Comment by exiawsh** [comment]
您好，对于memory的排序操作可以忽略，对性能没有影响。你可以取topk操作，用于略微减少显存消耗。

**Comment by nnop** [comment]
memory取topk是Focal-PETR提出的吧？
