### ISSUE TITLE
 the .pth files of the models on NuScenes test set

### ISSUE THREAD

**Issue by tingcuteee** [exiawsh/StreamPETR#153]
Could you provide me with the .pth files of the models on NuScenes test set? My email address is 2495717403@qq.com. Thanks.
![1](https://github.com/exiawsh/StreamPETR/assets/127753276/54dcaed4-f355-400e-a3ad-0dc064ac08e6)

**Comment by exiawsh** [comment]
Sorry, we have no quota to reproduce the results. There are some differences between our internal code and the code we are releasing now. We can provide you the config, you should train the model yourself.
