### ISSUE TITLE
r50的结果不理想

### ISSUE THREAD

**Issue by SYH9905** [exiawsh/StreamPETR#155]
mAP: 0.4316
mATE: 0.6457
mASE: 0.2680
mAOE: 0.4359
mAVE: 0.2612
mAAE: 0.1925
NDS: 0.5355
Eval time: 155.5s

Per-class results:
Object Class        	AP    	ATE   	ASE   	AOE   	AVE   	AAE   
car                 	0.633 	0.430 	0.148 	0.066 	0.249 	0.195 
truck               	0.408 	0.644 	0.209 	0.108 	0.195 	0.170 
bus                 	0.404 	0.880 	0.215 	0.155 	0.495 	0.285 
trailer             	0.147 	1.091 	0.224 	0.460 	0.188 	0.101 
construction_vehicle	0.131 	0.978 	0.488 	1.071 	0.121 	0.388 
pedestrian          	0.504 	0.618 	0.291 	0.542 	0.325 	0.164 
motorcycle          	0.458 	0.562 	0.263 	0.484 	0.358 	0.233 
bicycle             	0.393 	0.495 	0.251 	0.904 	0.158 	0.003 
traffic_cone        	0.652 	0.364 	0.312 	nan   	nan   	nan   
barrier             	0.586 	0.396 	0.280 	0.133 	nan   	nan  
请问这结果是可以接受的么（您提供的ck为NDS 54.6 mAP44.9），或者我们可以提供其他的方式提高我们的精度？

**Comment by exiawsh** [comment]
这个结果确实存在复现问题，但是您的结果也不是特别异常。可以尝试略微增加query数量。比如将topk_proposal设置为300，memory_len设置为600。
