### ISSUE TITLE
[EVA02] LearningRateDecayOptimizerConstructor 'decay_type': 'vit_wise'

### ISSUE THREAD

**Issue by billbliss3** [exiawsh/StreamPETR#156]
It seems no 'vit_wise' type in LearningRateDecayOptimizerConstructor functions.

**Comment by exiawsh** [comment]
@billbliss3 We didn't release the code for LearningRateDecayOptimizerConstructor. You should implement yourself.

**Comment by billbliss3** [comment]
@exiawsh 
Hi, I am confuse about the parameter 'weight_decay=1e-7' in vit_wise mode.

Why the 2 version of param have a large diff: weight_decay 1e-2 to 1e-7

    optimizer = dict(
        type='AdamW', 
        lr=4e-4, # bs 8: 2e-4 || bs 16: 4e-4
        paramwise_cfg=dict(
            custom_keys={
                'img_backbone': dict(lr_mult=0.1), 
            }),
        weight_decay=0.01)



    optimizer = dict(constructor='LearningRateDecayOptimizerConstructor',     
        type='AdamW', 
        lr=1e-4, betas=(0.9, 0.999), weight_decay=1e-7,
        paramwise_cfg={'decay_rate': 0.9,
                    'head_decay_rate': 4.0,
                    'decay_type': 'vit_wise',
                    'num_layers': 24,
                    })

**Comment by exiawsh** [comment]
@billbliss3 They have similar results. weght decay is not very important.

**Comment by billbliss3** [comment]
Hi, could you explain the meaning param head_decay_rate, I am a little confused.
@exiawsh 

'head_decay_rate': 4.0

**Comment by exiawsh** [comment]
@billbliss3 The learning rate of the detection head (4e-4) is 4x base_learning rate (1e-4).

**Comment by billbliss3** [comment]
您好，您的来件已收到，我会尽快给您回复的。

Thanks for you e-mail.~~
I've got it and I will reply it as soon as possible .

**Comment by yingfei1016** [comment]
@billbliss3 You can refer to this code
https://github.com/wenyuqing/panacea/blob/main/metrics/StreamPETR/projects/mmdet3d_plugin/models/utils/layer_decay_optimizer_constructor.py
