### ISSUE TITLE
the function of img_roi_head 

### ISSUE THREAD

**Issue by RouDanCongJii** [exiawsh/StreamPETR#159]
hallo, 
i want to know the function of img_roi(focal_head) is to get the topk index or any other information? and the function of the prepare for dn is it necessary for the training? And what is the cone means, which is the position embedding in Streampert_head.py

**Comment by bigliuyq** [comment]
+1，can we remove the img_roi(focal_head) ?

**Comment by exiawsh** [comment]
Sorry for late response. The img_roi head can be removed during inference.
