### ISSUE TITLE
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

### ISSUE THREAD

**Issue by chenxinhe1** [exiawsh/StreamPETR#161]
File "/home/cxh/StreamPETR-main/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 403, in position_embeding
    img2lidars = data['lidar2img'].inverse()
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1362164) of binary: /home/cxh/anaconda3/envs/streampetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
出现了这个问题，然后我把img2lidars = data['lidar2img'].inverse()中的.inverse()去掉，就能跑起来，但是loss很快就为0，请问怎么解决，盼复！！！

**Comment by exiawsh** [comment]
这个问题是由于你的gpu的驱动不支持或者你的显卡型号有点新导致的（比如笔记本的4060）。你可以把inverse过程放到cpu上，然后用numpy实现，之后再转到gpu上。

**Comment by chenxinhe1** [comment]
File "/home/cxh/StreamPETR-main/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 403, in position_embeding
img2lidars = data['lidar2img'].inverse()
RuntimeError: CUDA error: operation not supported when calling cusparseCreate(handle)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1362164) of binary: /home/cxh/anaconda3/envs/streampetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
单卡4090训练时候出现了上述问题。然后我把img2lidars = data['lidar2img'].inverse()中的.inverse()过程放到了cpu上，然后用numpy实现，之后再转到gpu上。操作如下：
404#img2lidars = data['lidar2img'].inverse() #源代码
405 img2lidars_torch = data['lidar2img'].inverse() #改
img2lidars_numpy = img2lidars_torch.detach.cpu().numpy()#改
img2lidars_numpy_inverse = inverse(img2lidars_numpy) #改
img2lidars_gpu = torch.from_numpy(img2lidars_numpy_inverse).to('cuda')#改
img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
img2lidars = topk_gather(img2lidars, topk_indexes)
![1](https://github.com/exiawsh/StreamPETR/assets/81944388/635a3bb6-66d4-473e-9efa-d4a993daf2b6)

但是仍然有这个错误
File "/home/cxh/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 405, in position_embeding
img2lidars_torch = data['lidar2img'].inverse() #改
RuntimeError: CUDA error: operation not supported when calling cusparseCreate(handle)
2024-02-28 15-20-04 的屏幕截图
请问怎么解决，盼复！！！
![2](https://github.com/exiawsh/StreamPETR/assets/81944388/6c124dd9-eed7-4518-b139-c7c15974f203)

**Comment by Terencedu** [comment]
![截图 2024-03-27 17-11-12](https://github.com/exiawsh/StreamPETR/assets/102672687/c6a4db81-f92a-4c8d-a783-e2294163da62)
这个代码可以运行，作者在其他issue回复过
