### ISSUE TITLE
sliding window in custom nuscenes dataloader

### ISSUE THREAD

**Issue by ETbaty** [exiawsh/StreamPETR#163]
in the case of sliding window do you have a mechanism to prevent sliding window that consists 2 different scene_tokens ? 
or is it just randomly happening without any effect on learning ?

**Comment by exiawsh** [comment]
@ETbaty We use prev_exist flag to reset the memory.
input_dict['scene_token'] != prev_scene_token:
                    input_dict.update(dict(prev_exists=False))

**Comment by ETbaty** [comment]
thank you for the quick response !
