### ISSUE TITLE
Diable Flash Attention

### ISSUE THREAD

**Issue by caichuang0415** [exiawsh/StreamPETR#166]
Thanks for sharing your codes！
My GPU does not support flash attention, I want to know how to diable it and use  normal attention instead.
![036d132edb1741b3e45c44dff826964](https://github.com/exiawsh/StreamPETR/assets/50684798/7e7e1980-f9ff-4c1c-abe2-dc62857a9d9b)

**Comment by exiawsh** [comment]
Hi, you can check this issue. You need to comment some lines in the code. https://github.com/exiawsh/StreamPETR/issues/23#issuecomment-1595663558
And change the config

**Comment by caichuang0415** [comment]
> Hi, you can check this issue. You need to comment some lines in the code. [#23 (comment)](https://github.com/exiawsh/StreamPETR/issues/23#issuecomment-1595663558) And change the config

sorry I just read it now and thank you for your reply
