### ISSUE TITLE
Passing a Sequence of choice from the Dataset

### ISSUE THREAD

**Issue by GUE1RNG** [exiawsh/StreamPETR#170]
Hello again :)

I want to pass only one scene rather than passing all the scenes in test dataset, how is it possible? 
I have a scene index and i want to input just the scene index, I was wondering it can be done in nuscenes_dataset.py. It can be done for desired camera, but wasnt able to do it for a specific scene.

Any insights would be good.

**Comment by GUE1RNG** [comment]
I hope my question is clear :)

**Comment by exiawsh** [comment]
@GUE1RNG 
self.data_infos = self.data_infos[:20]
You can use a subset of data_info when the dataset is initialized. Use a single GPU for testing, otherwise the scene will be split to different Gpus

**Comment by GUE1RNG** [comment]
Understood, Thanks a lot!

**Comment by GUE1RNG** [comment]
One more thing,
do we only have the ckpt for model trained on 8 frames or also one trained for less / more frames?

**Comment by exiawsh** [comment]
@GUE1RNG 
You can change the config here when using sliding window training,
https://github.com/exiawsh/StreamPETR/blob/2315cf9f077817ec7089c87094ba8a63f76c2acf/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs1_8key_2grad_24e.py#L21
When use stream training you should change the following config:
https://github.com/exiawsh/StreamPETR/blob/2315cf9f077817ec7089c87094ba8a63f76c2acf/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py#L211
window_size = 40 // seq_split_num
