### ISSUE TITLE
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

### ISSUE THREAD

**Issue by chenxinhe1** [exiawsh/StreamPETR#172]
File "/home/cxh/StreamPETR-main/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 403, in position_embeding
img2lidars = data['lidar2img'].inverse()
RuntimeError: CUDA error: operation not supported when calling cusparseCreate(handle)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1362164) of binary: /home/cxh/anaconda3/envs/streampetr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
单卡4090训练时候出现了上述问题。然后我把img2lidars = data['lidar2img'].inverse()中的.inverse()过程放到了cpu上，然后用numpy实现，之后再转到gpu上。操作如下：
404#img2lidars = data['lidar2img'].inverse() #源代码
405  img2lidars_torch = data['lidar2img'].inverse() #改
        img2lidars_numpy = img2lidars_torch.detach.cpu().numpy()#改
        img2lidars_numpy_inverse = inverse(img2lidars_numpy) #改
        img2lidars_gpu = torch.from_numpy(img2lidars_numpy_inverse).to('cuda')#改
        img2lidars = img2lidars.view(BN, 1, 1, 4, 4).repeat(1, H*W, D, 1, 1).view(B, LEN, D, 4, 4)
        img2lidars = topk_gather(img2lidars, topk_indexes)
![2024-02-28 15-18-57 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/81944388/1f851689-a04e-4123-8ff3-18b056024b5e)

但是仍然有这个错误
 File "/home/cxh/StreamPETR/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py", line 405, in position_embeding
    img2lidars_torch = data['lidar2img'].inverse() #改
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
![2024-02-28 15-20-04 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/81944388/1ae74d67-3e8a-46a8-9c42-c1a6b60dc457)
请问怎么解决，盼复！！！

**Comment by exiawsh** [comment]
你在405行仍然使用pytorch进行求逆，实现仍然存在问题，正确的方式类似于这样：
lidar2img = data['lidar2img].cpu().numpy
img2lidars = numpy.linalg.inv(lidar2img).to(data['lidar2img].device())

**Comment by chenxinhe1** [comment]
按照您说的方法，我使用
lidar2img = data['lidar2img].cpu().numpy
img2lidars = numpy.linalg.inv(lidar2img).to(data['lidar2img].device())，如图：
![2024-02-28 19-44-13 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/81944388/6fbfe6d3-8168-42f4-9688-749f9c012a0a)

结果出现了错误：File "/home/cxh/anaconda3/envs/streampetrmain/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 197, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional如图
![2024-02-28 19-44-38 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/81944388/ce6826a5-3935-4bd8-bca6-270e3a1f34c5)

之后，我修改代码如下即可运行进行训练，但是训练结果还未知：
        lidar2img = data['lidar2img'].cpu().numpy() #改1
        lidar2img_tensor = torch.from_numpy(lidar2img) #改2
        img2lidars = torch.inverse(lidar2img_tensor).to(data['lidar2img'].device) #改2
如图：
![2024-02-28 20-12-16 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/81944388/35cfd245-8f0d-49e8-ac3c-4911b67779cf)

请问，我这样修改是否合理呢？盼复！！！

**Comment by exiawsh** [comment]
。。。正常来讲你这么修改还是会报错，你需要用Numpy的接口求逆。。。

**Comment by chenxinhe1** [comment]
稍等，我再试一下
