### ISSUE TITLE
question for outputs_coord format in streampetr head

### ISSUE THREAD

**Issue by RouDanCongJii** [exiawsh/StreamPETR#174]
Here is the code in PETR 
`tmp = self.reg_branches[lvl](outs_dec[lvl])`
`tmp[..., 0:2] += reference[..., 0:2]`
`tmp[..., 0:2] = tmp[..., 0:2].sigmoid()`
`tmp[..., 4:5] += reference[..., 2:3]`
`tmp[..., 4:5] = tmp[..., 4:5].sigmoid()`
in streamPETR 
`tmp[..., 0:3] += reference[..., 0:3]`
`tmp[..., 0:3] = tmp[..., 0:3].sigmoid()`
 why is the format isdiffernet

**Comment by exiawsh** [comment]
Hi, you can compare the following:
The order is changed
https://github.com/megvii-research/PETR/blob/f7525f93467a33707ef401c587a52d5e7b34de74/projects/mmdet3d_plugin/core/bbox/util.py#L51
https://github.com/exiawsh/StreamPETR/blob/2315cf9f077817ec7089c87094ba8a63f76c2acf/projects/mmdet3d_plugin/core/bbox/util.py#L15

**Comment by RouDanCongJii** [comment]
if my label format of mya dataset is cx, cy, cz ,l, w, h,r is ther any influence or should i change into  cx, cy, cz ,w, l, h,r

**Comment by exiawsh** [comment]
If you are not involved in the evaluation on the nuScenes dataset, then it can be changed.

**Comment by RouDanCongJii** [comment]
another question is that, if the memory_queue store 4 frame information, the current frame_idx is e.g. 100, the frame_idx in memory_queue is random or 96, 97, 98, 99
