### ISSUE TITLE
多目标跟踪的问题

### ISSUE THREAD

**Issue by hanzifan** [exiawsh/StreamPETR#175]
您好，我想运行跟踪代码，指令如下
```
python nusc_tracking/pub_test.py --version v1.0-trainval --checkpoint ./test/stream_petr_r50_flash_704_bs2_seq_24e/Fri_Mar__1_20_24_11_2024/pts_bbox/results_n
usc.json --data_root ./data/nuscenes/
```
却得到如下报错
`
ValueError: Length of names must match number of levels in MultiIndex.
`

**Comment by exiawsh** [comment]
Hi, please refer to https://github.com/exiawsh/StreamPETR/issues/72#issuecomment-1674208380

**Comment by hanzifan** [comment]
Thanks for replying. I installed motmetrics in version 1.1.3. Here, but I got another bug.
`
TypeError: can only concatenate tuple (not "int") to tuple
`

**Comment by exiawsh** [comment]
https://github.com/exiawsh/StreamPETR/issues/72#issuecomment-1668881524

**Comment by hanzifan** [comment]
Thanks. I reinstall pandas in 1.5.0, it's correct.
