### ISSUE TITLE
Input only the desired sequence

### ISSUE THREAD

**Issue by GUE1RNG** [exiawsh/StreamPETR#176]
Hello

I want to pass only one sequence rather than passing all the 1000 sequences!

I edited the following line:

info = self.data_infos[index]

BUT, the "index" here is for each sample not for each sequence i guess. I want to pass only one sequence and I know the sequence index. Even though i filtered it on the basis of scene_token, the evaluation still iterates over the same sequence again and again.

Any insights would be good.

**Comment by exiawsh** [comment]
Hi
You need change self.date_infos in the init function of the dataset rather than get_data_info

**Comment by GUE1RNG** [comment]
I did that, it didnt work. Displayed the error "AssertionError: Samples in split doesn't match samples in predictions."

**Comment by exiawsh** [comment]
You need to modify the code in the nuscenes evaluation pipeline yourself.
https://github.com/nutonomy/nuscenes-devkit/issues/263
