### ISSUE TITLE
latest.pth for nuscense dataset is not available anywhere

### ISSUE THREAD

**Issue by Joechencc** [exiawsh/StreamPETR#18]
Hi, I am quite interested in this work, especially for its comparable results to the lidar object detection.  I was trying to regenerate your visualizations without training it. However, I am not able to find a good "latest.pth" for the model. I tried to use dd3d_det_final.pth as below.

./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py ckpts/dd3d_det_final.pth 1 --format-only --eval-options 'jsonfile_prefix=results/bevfusion-det-val-predictions

However, the "results_nusc.json" does not seem to be correct? Other than trained by myself, can you offer a good latest.pth for me to test on Nuscense dataset

**Comment by HMPgit** [comment]
May I ask which checkpoint and Config file. I am also having the same issue. Thank you.

**Comment by Joechencc** [comment]
The one I am using is the one I listed

**Comment by Joechencc** [comment]
DO use this pth stream_petr_vov_flash_800_bs2_seq_24e.pth

**Comment by Joechencc** [comment]
https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth

**Comment by Joechencc** [comment]
./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py ckpts/stream_petr_vov_flash_800_bs2_seq_24e.pth 1 --format-only --eval-options 'jsonfile_prefix=results/bevfusion-det-val-predictions'
