### ISSUE TITLE
关于速度估计

### ISSUE THREAD

**Issue by Gaondong** [exiawsh/StreamPETR#182]
为什么速度直接学习了绝对速度？如果学习相对速度会不会更好一些。

**Comment by Gaondong** [comment]
> 之前尝试过相对速度估计，效果不理想。首先，ego_pose信息泄露了自车速度，所以这个信息是存在的，网络可以回归绝对速度。其次，大部分物体都是静止的，速度为0，回归相对速度，分布就会偏移0，网络初始收敛效果不好。

感谢您的回复，请问ego_pose信息泄露了自车速度指的是local坐标系转换和timestamp delta 暗含了自车速度信息吗？看起来代码中并没有直接提到自车速度。

**Comment by exiawsh** [comment]
是的，global坐标系转换和timestamp delta 暗含了自车速度信息

**Comment by Gaondong** [comment]
明白了，感谢回复.



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: exiawsh ***@***.***&gt;
发送时间: 2024年4月1日 19:30
收件人: exiawsh/StreamPETR ***@***.***&gt;
抄送: jiandong.gao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [exiawsh/StreamPETR] 关于速度估计 (Issue #182)





 
是的，global坐标系转换和timestamp delta 暗含了自车速度信息
