### ISSUE TITLE
How to calculate the 'resize_lim' paras?

### ISSUE THREAD

**Issue by cmiforsaken** [exiawsh/StreamPETR#183]
ida_aug_conf = {
"resize_lim": (, ),
"final_dim": (1536, 1536),
"bot_pct_lim": (0.0, 0.0),
"rot_lim": (0.0, 0.0),
"H": 900,
"W": 1600,
"rand_flip": True,
}
My image size is 900x1600，final_dim is (1536, 1536), how to set best resize_lim parameter?

**Comment by cmiforsaken** [comment]
I set the paras [0.625, 1.2], is right?

**Comment by cmiforsaken** [comment]
I set the paras [0.675, 1.2], is right?

**Comment by exiawsh** [comment]
No, You can set image resolution to (1600, 800) and set paras to (0.94, 1.25). Using square input is slightly more complicate.

**Comment by cmiforsaken** [comment]
I have done this paras exp. But I want to try [1536, 1536] resolution, so how to set the 'resize_lim' paras?😂

**Comment by yingfei1016** [comment]
The IDA is not support crop a image larger than the origin image size. So 1536x1536 should be processed twice.
(1) set image resolution to (1600, 800) and set paras to (0.94, 1.25). 
(2) https://github.com/megvii-research/PETR/blob/main/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L116 This code may need to be check, since it is based on mmdet3d 0.17.

**Comment by yingfei1016** [comment]
<img width="662" alt="1712049221429_3BF60062-E4FE-4d3e-BE9C-56E7D7BCCBCB" src="https://github.com/exiawsh/StreamPETR/assets/106943722/9132aed5-2bde-4381-b898-ccd059d5e6d4">

**Comment by cmiforsaken** [comment]
I'll try. Thanks!

**Comment by yingfei1016** [comment]
@cmiforsaken You can also refer to this code，it is the final code but a little complex by diffusion task.

https://github.com/wenyuqing/panacea/blob/main/metrics/StreamPETR/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L755

**Comment by cmiforsaken** [comment]
> @cmiforsaken You can also refer to this code，it is the final code but a little complex by diffusion task.
> 
> https://github.com/wenyuqing/panacea/blob/main/metrics/StreamPETR/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L755

Thanks, I'll try.
