### ISSUE TITLE
position_embeding question

### ISSUE THREAD

**Issue by xuanzhangyang** [exiawsh/StreamPETR#184]
position_embeding函数中coords[..., :2] = coords[..., :2] * torch.maximum(coords[..., 2:3], torch.ones_like(coords[..., 2:3])*eps)，应该表示的是用memory_centers * coords_d， 为什么要让这两个相乘？目的是啥呢，没搞明白，还望解答

**Comment by exiawsh** [comment]
您好，这一步是求视椎体射线

**Comment by xuanzhangyang** [comment]
对这一步如何求视椎体射线不是很明白，请问有没有原理介绍？或者文章可以看看，原谅我还没入门^v^

**Comment by xuanzhangyang** [comment]
好的，感谢科普，理解了
