### ISSUE TITLE
远处目标有较多重影，近处同向目标较为正常，应如何解决

### ISSUE THREAD

**Issue by Gaondong** [exiawsh/StreamPETR#186]
你好，我使用streampetr训练了前视三个相机数据，发现存在远处目标学习不好，有重复检测的情况，当前可视化confidence 阈值为0.2，请问有什么方式可以解决吗，depth分布使用的LID，这是否会有影响
![image](https://github.com/exiawsh/StreamPETR/assets/43692998/6c261a2e-1a73-48d7-afc1-7d4d3c501d82)

**Comment by exiawsh** [comment]
不需要更改depth分布。是否有尝试过延长训练时间，通常30米以上就会出现较多重影。可以参考下面的方法解决，使用query denosing构造类似的FP样本进行学习；
https://github.com/LiewFeng/RayDN 或者
https://github.com/megvii-research/Far3D

**Comment by Gaondong** [comment]
> 不需要更改depth分布。是否有尝试过延长训练时间，通常30米以上就会出现较多重影。可以参考下面的方法解决，使用query denosing构造类似的FP样本进行学习； https://github.com/LiewFeng/RayDN 或者 https://github.com/megvii-research/Far3D

还没有尝试过延长时间，当前有300万bundle数据，bs=8*8gpu，训练时长为46万次迭代（10 epoch），学习率为4e-4，请问应该如何调整

**Comment by exiawsh** [comment]
学习率6e-4，应该不需要延长时间。主要是模型问题，试一下我提的那两个query denosing和deformable attention

**Comment by Gaondong** [comment]
好的 感谢 &nbsp;我再试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: exiawsh ***@***.***&gt;
发送时间: 2024年4月8日 12:27
收件人: exiawsh/StreamPETR ***@***.***&gt;
抄送: jiandong.gao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [exiawsh/StreamPETR] 远处目标有较多重影，近处同向目标较为正常，应如何解决 (Issue #186)





 
学习率6e-4，应该不需要延长时间。主要是模型问题，试一下我提的那两个query denosing和deformable attention

**Comment by Gaondong** [comment]
> 学习率6e-4，应该不需要延长时间。主要是模型问题，试一下我提的那两个query denosing和deformable attention

![image](https://github.com/exiawsh/StreamPETR/assets/43692998/a5b760ca-d8cd-4967-8d35-b0a81db81acd)
看起来rag-denosing还使用了多尺度，且3D position embedding也有所不同，我当前是只需要把这个工程中ray-denoise相关的代码拿到streampetr head中试试吗？

**Comment by sjminInSwm** [comment]
What kind of learning data did you use?

nuscene? or custom data?

@Gaondong  thank you!

**Comment by Amireux52** [comment]
> 你好，我使用streampetr训练了前视三个相机数据，发现存在远处目标学习不好，有重复检测的情况，当前可视化confidence 阈值为0.2，请问有什么方式可以解决吗，depth分布使用的LID，这是否会有影响 ![image](https://private-user-images.githubusercontent.com/43692998/320345163-6c261a2e-1a73-48d7-afc1-7d4d3c501d82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzU0MTQsIm5iZiI6MTcyNTQzNTExNCwicGF0aCI6Ii80MzY5Mjk5OC8zMjAzNDUxNjMtNmMyNjFhMmUtMWE3My00OGQ3LWFmYzEtN2Q0ZDNjNTAxZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA3MzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZjE0MmNjYWZmMWUwMjMzMzM4NjRmMDEyMTE2Y2RlYjkwODk4NTEwZGVlNGM0N2EzYjY4OWFjMmU5Mjc5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ep9YWIDXnVQkXLvOPZip9BBnVDF8OP8vNYeYeoB9ZaY)
老师您好，请问这种带坐标的可视化结果图是如何生成的呀，作者给出的可视化代码生成的图并没有坐标呀，盼复，谢谢啦

**Comment by Gaondong** [comment]
用plt画完bev下的图和目标以后再和摄像头图做拼接。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Amireux52 ***@***.***&gt;
发送时间: 2024年9月7日 19:15
收件人: exiawsh/StreamPETR ***@***.***&gt;
抄送: jiandong.gao ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [exiawsh/StreamPETR] 远处目标有较多重影，近处同向目标较为正常，应如何解决 (Issue #186)





  
你好，我使用streampetr训练了前视三个相机数据，发现存在远处目标学习不好，有重复检测的情况，当前可视化confidence 阈值为0.2，请问有什么方式可以解决吗，depth分布使用的LID，这是否会有影响 
 老师您好，请问这种带坐标的可视化结果图是如何生成的呀，作者给出的可视化代码生成的图并没有坐标呀，盼复，谢谢啦

**Comment by Amireux52** [comment]
> 用plt画完bev下的图和目标以后再和摄像头图做拼接。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Amireux52 ***@***.***&gt; 发送时间: 2024年9月7日 19:15 收件人: exiawsh/StreamPETR ***@***.***&gt; 抄送: jiandong.gao ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [exiawsh/StreamPETR] 远处目标有较多重影，近处同向目标较为正常，应如何解决 (Issue #186) 你好，我使用streampetr训练了前视三个相机数据，发现存在远处目标学习不好，有重复检测的情况，当前可视化confidence 阈值为0.2，请问有什么方式可以解决吗，depth分布使用的LID，这是否会有影响 老师您好，请问这种带坐标的可视化结果图是如何生成的呀，作者给出的可视化代码生成的图并没有坐标呀，盼复，谢谢啦 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

老师，可以把这个可视化的代码分享一份吗，不甚感激，谢谢您啦，echochenxinhe@126.com
