### ISSUE TITLE
Precision and recall for all the classes

### ISSUE THREAD

**Issue by GUE1RNG** [exiawsh/StreamPETR#187]
Hello,
For some evaluation, I want the precision and recall for all classes, where can i get that from?

Thanks :)

**Comment by exiawsh** [comment]
nuscenes evaluation provide the implementation to draw the PR curve like this:
You may delete this line:
https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/mmdet3d/datasets/nuscenes_dataset.py#L514
and save the tmp_dir which could show you the PR curve like this:
![image](https://github.com/exiawsh/StreamPETR/assets/74858581/e6455cc7-2390-499b-ac5d-659977eba66d)

**Comment by GUE1RNG** [comment]
Understood, thanks :)
