### ISSUE TITLE
What is the meaning of config file?

### ISSUE THREAD

**Issue by Jason-Du111** [exiawsh/StreamPETR#192]
![image](https://github.com/exiawsh/StreamPETR/assets/81087239/e3341d5b-52d9-4c7c-802a-8528fe6d002e)
i wondering:
- What is the meaning of vov/r50?
- What is the meaning of flash?
- What is the meaning of 704/800?
- What is the meaning of seq?
- What is the meaning of 90e/24e?

thanks so much!

**Comment by exiawsh** [comment]
1. vov/r50 is the backbone type
2. flash is flash_attention
3. 704/800 is the width of  the image (resolution)
4. seq is the training method (sampler) sliding window/seq training
5. 90e/24e is the number of epoch.
