### ISSUE TITLE
after change the config file, it still need flash attn,

### ISSUE THREAD

**Issue by MillionaireChen** [exiawsh/StreamPETR#193]
@jojolee123  Have you changed the config of flash attn? 
You should change type='PETRMultiheadFlashAttention' to type='PETRMultiheadAttention'. If you change this config, thr line78 will not be used.

_Originally posted by @exiawsh in https://github.com/exiawsh/StreamPETR/issues/23#issuecomment-1595665447_

------------------------------------------------------------------
Hi, thanks for your works!
I am currently learning your code and paper.

I modify the code this way. But it still needs the "flash_attn". I don't know if I correctly modified the code.

<img width="1291" alt="image" src="https://github.com/exiawsh/StreamPETR/assets/35960345/54c8af55-8705-41ee-be87-c64c818d7cb6">
<img width="1304" alt="image" src="https://github.com/exiawsh/StreamPETR/assets/35960345/491cf1c4-e9ba-4c88-bd78-6c7379443909">

<img width="1304" alt="image" src="https://github.com/exiawsh/StreamPETR/assets/35960345/e3ff385b-2fce-4436-9385-53390027a6dd">

In "projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py"
                       dict(
                            type='PETRMultiheadAttention',
                            embed_dims=256,
                            num_heads=8,
                            dropout=0.1),
                        ],

In "projects/mmdet3d_plugin/models/utils/petr_transformer.py"
                from mmcv.utils import deprecated_api_warning, ConfigDict
                import copy
                from torch.nn import ModuleList
                # from .attention import FlashMHA
                import torch.utils.checkpoint as cp
                from mmcv.runner import auto_fp16

I run "python tools/train.py projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py --work-dir work_dirs/run1/" on MacBook pytorch CPU with nuscenes v1.0 mini

error:
projects.mmdet3d_plugin
Traceback (most recent call last):
  File "tools/train.py", line 274, in <module>
    main()
  File "tools/train.py", line 134, in main
    plg_lib = importlib.import_module(_module_path)
  File "/opt/miniconda3/envs/pstr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chen/PycharmProjects/StreamPETR/projects/mmdet3d_plugin/__init__.py", line 9, in <module>
    from .models.backbones import *
  File "/Users/chen/PycharmProjects/StreamPETR/projects/mmdet3d_plugin/models/backbones/__init__.py", line 9, in <module>
    from .eva_vit import EVAViT
  File "/Users/chen/PycharmProjects/StreamPETR/projects/mmdet3d_plugin/models/backbones/eva_vit.py", line 14, in <module>
    from ..utils.attention import FlashAttention, FlashMHA
  File "/Users/chen/PycharmProjects/StreamPETR/projects/mmdet3d_plugin/models/utils/attention.py", line 21, in <module>
    from flash_attn.flash_attn_interface import flash_attn_unpadded_kvpacked_func
ModuleNotFoundError: No module named 'flash_attn'

Package                   Version            Editable project location
------------------------- ------------------ ----------------------------------------------------
absl-py                   2.1.0
addict                    2.4.0
aliyun-python-sdk-core    2.15.1
aliyun-python-sdk-kms     2.16.2
appnope                   0.1.4
asttokens                 2.4.1
attrs                     23.2.0
backcall                  0.2.0
black                     24.4.2
blinker                   1.8.1
cachetools                5.3.3
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
ConfigArgParse            1.7
crcmod                    1.7
cryptography              42.0.6
cycler                    0.12.1
dash                      2.17.0
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
decorator                 5.1.1
descartes                 1.1.0
einops                    0.8.0
exceptiongroup            1.2.1
executing                 2.0.1
fastjsonschema            2.19.1
fire                      0.6.0
flake8                    7.0.0
Flask                     3.0.3
fonttools                 4.51.0
fvcore                    0.1.5.post20221221
google-auth               2.29.0
google-auth-oauthlib      1.0.0
grpcio                    1.63.0
idna                      3.7
imageio                   2.34.1
importlib_metadata        7.1.0
importlib_resources       6.4.0
iniconfig                 2.0.0
iopath                    0.1.10
ipython                   8.12.3
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.3
jmespath                  0.10.0
joblib                    1.4.2
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter_core              5.7.2
kiwisolver                1.4.5
llvmlite                  0.36.0
lyft-dataset-sdk          0.0.8
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.5.3
matplotlib-inline         0.1.7
mccabe                    0.7.0
mdurl                     0.1.2
mkl-fft                   1.3.1
mkl-random                1.2.2
mkl-service               2.4.0
mmcls                     0.25.0
mmcv-full                 1.6.0
mmdet                     2.28.2
mmdet3d                   1.0.0rc6           /Users/chen/PycharmProjects/StreamPETR/mmdetection3d
mmsegmentation            0.30.0
model-index               0.1.11
mypy-extensions           1.0.0
nbformat                  5.7.0
nest-asyncio              1.6.0
networkx                  2.2
numba                     0.53.0
numpy                     1.21.4
nuscenes-devkit           1.1.11
oauthlib                  3.2.2
open3d                    0.17.0
opencv-python             4.9.0.80
opendatalab               0.0.10
openmim                   0.3.9
openxlab                  0.0.38
ordered-set               4.1.0
oss2                      2.17.0
packaging                 24.0
pandas                    2.0.3
parso                     0.8.4
pathspec                  0.12.1
pexpect                   4.9.0
pickleshare               0.7.5
Pillow                    9.3.0
pip                       23.3.1
pkgutil_resolve_name      1.3.10
platformdirs              4.2.1
plotly                    5.22.0
pluggy                    1.5.0
plyfile                   1.0.3
portalocker               2.8.2
prettytable               3.10.0
prompt-toolkit            3.0.43
protobuf                  5.26.1
ptyprocess                0.7.0
pure-eval                 0.2.2
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycocotools               2.0.7
pycodestyle               2.11.1
pycparser                 2.22
pycryptodome              3.20.0
pyflakes                  3.2.0
Pygments                  2.18.0
pyparsing                 3.1.2
pyquaternion              0.9.9
pytest                    8.2.0
python-dateutil           2.9.0.post0
pytz                      2023.4
PyWavelets                1.4.1
PyYAML                    6.0.1
referencing               0.35.1
requests                  2.28.2
requests-oauthlib         2.0.0
retrying                  1.3.4
rich                      13.4.2
rpds-py                   0.18.0
rsa                       4.9
scikit-image              0.19.3
scikit-learn              1.3.2
scipy                     1.10.1
setuptools                60.2.0
Shapely                   1.8.5.post1
six                       1.16.0
stack-data                0.6.3
tabulate                  0.9.0
tenacity                  8.2.3
tensorboard               2.14.0
tensorboard-data-server   0.7.2
termcolor                 2.4.0
terminaltables            3.1.10
threadpoolctl             3.5.0
tifffile                  2023.7.10
tomli                     2.0.1
torch                     1.9.0
torchaudio                0.9.0a0+33b2469
torchvision               0.10.0
tqdm                      4.65.2
traitlets                 5.14.3
trimesh                   2.35.39
typing_extensions         4.9.0
tzdata                    2024.1
urllib3                   1.26.18
wcwidth                   0.2.13
Werkzeug                  3.0.2
wheel                     0.43.0
yacs                      0.1.8
yapf                      0.40.2
zipp                      3.18.1

**Comment by exiawsh** [comment]
Hi, 
We also use flash-attn in EVA-VIT. You should comment the code in EVA and do not use flash attention in EVA.
from ..utils.attention import FlashAttention, FlashMHA comment this
and modify the config
flash_attn=False in the image backbone
