### ISSUE TITLE
感谢您的优秀工作，关于reset memory我有个问题，通过调试我发现是窗口20帧，但每个batch都会进行reset重置为none，请问memory bank是怎么更新的呢？

### ISSUE THREAD

**Issue by loserhou** [exiawsh/StreamPETR#195]

**Comment by loserhou** [comment]
我可能没表达清楚，我理解的应该是每个batch都reset为none，初始帧初始化为0，之后得到top256拼接1024再取前1024这样迭代更新，但是下一个batch不是还会reset为none吗？这样还怎么进行更新呢

**Comment by exiawsh** [comment]
只有场景切换才会reset memory，并不是每个mini batch都进行操作。
