### ISSUE TITLE
关于focalhead

### ISSUE THREAD

**Issue by loserhou** [exiawsh/StreamPETR#197]
训练时候numsampletokens就是特征图大小，topk操作其实还是使用了所有特征图位置进行排序，那这一步的目的是什么呢？希望得到您的回答

**Comment by loserhou** [comment]
还有一个问题，预测结果和gt的坐标位置是相对于自车吗？

**Comment by exiawsh** [comment]
在StreamPETR中我们并未进行采样，此步骤可以丢弃
