### ISSUE TITLE
Ego-pose is False then results are too poor!!! Please guide me

### ISSUE THREAD

**Issue by mdfaheem786** [exiawsh/StreamPETR#2]
Hi,

much appreciated with the work with good FPS and performance.

my set up is same - https://github.com/exiawsh/StreamPETR/issues/1

i am making false for this field with_ego_pose(https://github.com/exiawsh/StreamPETR/blob/main/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py#L82) as mention in paper - tab5 with out Ego pose, time and velocity. Below are the metrics.

![Screenshot_20230420_172416](https://user-images.githubusercontent.com/126733490/233322310-3e956b8f-ce09-4635-985a-7021f325707b.png)

please suggested me, how to disable (ego-pose).

thanking you in advance :)

**Comment by exiawsh** [comment]
Hi, if you want to disable the ego-pose embedding, you have to retrain the network. In our paper, **we retrain the network and set with_ego_pose to False.**

**Comment by mdfaheem786** [comment]
thank you @exiawsh, for your guidance and quick reply :)
