### ISSUE TITLE
ViT-Large Backbone in StreamPETR-large

### ISSUE THREAD

**Issue by FiveLu** [exiawsh/StreamPETR#20]
Hi, i'm very interested in your work and its very helpful for me. I have a few questions about the config of StreamPETR-large:

1. MIM-pretrained VIT-Large backbone ？  Is this the same as MMPretrain's ? 
2. The patch size is set to 16, right?
3. What about the img_neck?  Does it need to combine features from different layers in ViT?  if so, which layers?

Thanks very much!

**Comment by exiawsh** [comment]
1. It's a modified VIT-Large backbone, different from  MMPretrain's.
2. Patch size is set to 16.
3. No img_neck. A simple MLP to align the channel to 256.

**Comment by FiveLu** [comment]
> 1. It's a modified VIT-Large backbone, different from  MMPretrain's.
> 2. Patch size is set to 16.
> 3. No img_neck. A simple MLP to align the channel to 256.

@exiawsh  I want to know the details about your modified VIT-Large backbone. What is modified?  the network structure or other config parameters. Could you please share ? Thank you so much ！

**Comment by exiawsh** [comment]
@FiveLu Sorry, the setting of VIT-Large is still kept private. You can try InternImage or other modern backbones.
