### ISSUE TITLE
About test on nuscenes

### ISSUE THREAD

**Issue by Jason-Du111** [exiawsh/StreamPETR#200]
when i run test on nuscenes like this:
`bash tools/dist_test.sh projects/configs/DETR3D/detr3d_1600_bs4_gpu2_seq_24e.py ./detr/latest.pth 4 --format-only`
there raise error:
`AttributeError: 'ConcatDataset' object has no attribute 'format_results'`
how can i solve it ,thanks so much!

**Comment by AmbarishGK** [comment]
Hi Can you tell me what env setup did you use?

Cos I too am only trying to test but failing at the env setup and compatibilty issues
