### ISSUE TITLE
About the commands using in the “docs/training_inference.md” and the training results

### ISSUE THREAD

**Issue by MillionaireChen** [exiawsh/StreamPETR#201]
Hi, thanks for your work. Currently, I ran all of the commands of StreaPETR from scratch and got the results.  under "stream_petr_r50_flash_704_bs2_seq_24e", everything is ok.

I still have some questions. In the training_inference.md, we use "tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 4 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/
" for training.  "tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 4 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/"

I use 4 x 3090, disable flash_attn, and this is my result. 
mAP: 0.2572
mATE: 0.8238
mASE: 0.2923
mAOE: 0.8811
mAVE: 0.4235
mAAE: 0.2379
NDS: 0.3627
Eval time: 196.5s

Per-class results:
Object Class        	AP    	ATE   	ASE   	AOE   	AVE   	AAE   
car                 	0.460 	0.576 	0.162 	0.434 	0.374 	0.227 
truck               	0.207 	0.785 	0.239 	0.639 	0.315 	0.215 
bus                 	0.146 	0.898 	0.240 	0.270 	0.937 	0.289 
trailer             	0.029 	1.252 	0.264 	1.177 	0.314 	0.162 
construction_vehicle	0.012 	1.136 	0.543 	1.332 	0.127 	0.397 
pedestrian          	0.335 	0.815 	0.296 	0.951 	0.591 	0.350 
motorcycle          	0.274 	0.705 	0.293 	1.188 	0.504 	0.245 
bicycle             	0.259 	0.770 	0.270 	1.627 	0.226 	0.019 
traffic_cone        	0.446 	0.631 	0.333 	nan   	nan   	nan   
barrier             	0.405 	0.670 	0.283 	0.311 	nan   	nan   
I think this result is a little bit low, could I improve it?

**another question:** 
we use "tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --eval bbox" for evaluation. **When I use this, errors appear. so I use "stream_petr_r50_flash_704_bs2_seq_24e.py" to replace the "stream_petr_vov_flash_800_bs2_seq_24e". And it works.** 

So, I want to train "stream_petr_vov_flash_800_bs2_seq_24e", but errors appear.

Traceback (most recent call last):
  File "tools/train.py", line 268, in <module>
    main()
  File "tools/train.py", line 256, in main
    custom_train_model(
  File "/home/StreamPETR/projects/mmdet3d_plugin/core/apis/train.py", line 30, in custom_train_model
    custom_train_detector(
  File "/home/StreamPETR/projects/mmdet3d_plugin/core/apis/mmdet_train.py", line 202, in custom_train_detector
    runner.load_checkpoint(cfg.load_from)
  File "/home/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 349, in load_checkpoint
    return load_checkpoint(
  File "/home/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 627, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 561, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 303, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/home/anaconda3/envs/petr/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 322, in load_from_local
    raise FileNotFoundError(f'{filename} can not be found.')
FileNotFoundError: ckpts/fcos3d_vovnet_imgbackbone-remapped.pth can not be found.

**Comment by MillionaireChen** [comment]
Now I used 8 gpus, this is the results:

mAP: 0.3742
mATE: 0.6918
mASE: 0.2754
mAOE: 0.6189
mAVE: 0.2916
mAAE: 0.2243
NDS: 0.4769
Eval time: 174.0s

Per-class results:
Object Class        	AP    	ATE   	ASE   	AOE   	AVE   	AAE   
car                 	0.573 	0.475 	0.154 	0.112 	0.267 	0.214 
truck               	0.339 	0.720 	0.218 	0.190 	0.213 	0.197 
bus                 	0.302 	0.903 	0.229 	0.130 	0.587 	0.282 
trailer             	0.117 	1.118 	0.253 	0.650 	0.173 	0.207 
construction_vehicle	0.097 	0.932 	0.497 	1.289 	0.126 	0.437 
pedestrian          	0.436 	0.700 	0.285 	0.636 	0.388 	0.195 
motorcycle          	0.362 	0.654 	0.271 	1.032 	0.408 	0.255 
bicycle             	0.379 	0.530 	0.262 	1.364 	0.170 	0.007 
traffic_cone        	0.580 	0.447 	0.309 	nan   	nan   	nan   
barrier             	0.557 	0.439 	0.276 	0.167 	nan   	nan  

I think there are some improvements

**Comment by exiawsh** [comment]
You should adjust the learning rate and batch_size when change the number of gpus.
Please check the criteria here:
![image](https://github.com/exiawsh/StreamPETR/assets/74858581/f6138b20-1866-44c5-a6cf-6acd7e208054)

FileNotFoundError: ckpts/fcos3d_vovnet_imgbackbone-remapped.pth can not be found.
For this question, you should download our checkpoints:
![image](https://github.com/exiawsh/StreamPETR/assets/74858581/46e06758-9b97-4bad-a75b-0d88886f1a05)
https://github.com/exiawsh/storage/releases/download/v1.0/fcos3d_vovnet_imgbackbone-remapped.pth
