### ISSUE TITLE
temporal_alignment里当前query_pos应用MLN的目的是啥？

### ISSUE THREAD

**Issue by xuanzhangyang** [exiawsh/StreamPETR#205]
在temporal_alignment函数中，对当前query_pos使用MLN的目的是啥？以及为啥query_pos是和一个固定的对角矩阵concat上全0矩阵在进行nerf的位置编码后进行MLN？

**Comment by exiawsh** [comment]
您好，感谢关注。目前的版本是为了形式上的对齐，对当前query去除MLN也没有影响。在我们较早的版本中，我们是有一帧memory就concat一帧，如果是起始帧，就没有memory，MLN不对当前帧进行操作的话就会出现没有梯度回传的bug。但是当前的版本不会出现这个问题，可以去掉。

**Comment by loserhou** [comment]
> 在temporal_alignment函数中，对当前query_pos使用MLN的目的是啥？以及为啥query_pos是和一个固定的对角矩阵concat上全0矩阵在进行nerf的位置编码后进行MLN？

我也有这个疑惑，但是去掉会掉点。。。。

**Comment by xuanzhangyang** [comment]
> > 在temporal_alignment函数中，对当前query_pos使用MLN的目的是啥？以及为啥query_pos是和一个固定的对角矩阵concat上全0矩阵在进行nerf的位置编码后进行MLN？
> 
> 我也有这个疑惑，但是去掉会掉点。。。。

可能形式上的对齐模型更容易理解吧
