### ISSUE TITLE
streampetr_head.py中cone的作用是什麼？

### ISSUE THREAD

**Issue by jinpeifei2015** [exiawsh/StreamPETR#206]
您好，打扰您一下：
![Screenshot from 2024-06-04 19-54-29](https://github.com/exiawsh/StreamPETR/assets/15372959/ee3a7fd4-4f59-4a7f-8e4d-992be309f641)
图片中cone的作用是什么，为什么要这么做？cone中包含fx,fy及camera中部分3D位置编码

**Comment by loserhou** [comment]
可以看看focal-petr，是spatial-align

**Comment by dodeokwangyooo** [comment]
我也没看懂有无帅比 直接简单说一下呢
