### ISSUE TITLE
2.5D center

### ISSUE THREAD

**Issue by 1yuechu1** [exiawsh/StreamPETR#207]
您好，我在Focal-PETR论文中看到2.5D中心，请问一下，这里的2.5D中心是指的加上深度的信息吗。
我在StreamPETR的代码中发现，只具有center2d，针对于网格的中心增加了偏移生成centers2d_offset，这个和Focal-PETR中的2.5D中心好像对应不上，所以在StreamPETR中并没有使用2.5D中心吗。
十分期待您的回答，谢谢

**Comment by exiawsh** [comment]
您好，我们没有加入深度信息，只是增加了像素坐标的偏移量。

**Comment by 1yuechu1** [comment]
十分感谢您的回复
