### ISSUE TITLE
RepDETR3D连续帧采样逻辑

### ISSUE THREAD

**Issue by sms95** [exiawsh/StreamPETR#208]
请问RepDETR3D中连续帧采样是什么实现的，查看代码发现seq_mode和queue_length控制着prepare_train_data中index_list的生成，但是CustomNuScenesDataset的初始化把seq_mode 和 queue_length hard code 成了1导致index_list长度只有1. 如果基于上述理解要使用streaming 模式训练如何保证连续帧之间的信息传递？ 如果是slide window 模式又是如何保证的呢？

**Comment by exiawsh** [comment]
抱歉，回复的有点晚，请参考以下issue:
https://github.com/exiawsh/StreamPETR/issues/24#issuecomment-1573128569
Stream training不会使用queue_length，这个是sliding window的标志。streaming training依靠flag和batch_sampler进行视频帧的采样控制。
