### ISSUE TITLE
train+val作为训练集时，多卡训练NCCL超时报错，大佬可以看看吗？

### ISSUE THREAD

**Issue by loserhou** [exiawsh/StreamPETR#212]
![2ff08b367077445a0c34d34fc1e9f47](https://github.com/exiawsh/StreamPETR/assets/151776629/1372e31d-9036-4b31-ae83-4bc2b97d7a9e)

**Comment by exiawsh** [comment]
这个问题没遇到过，config发一下看看？

**Comment by loserhou** [comment]
问题已解决，请问可以提供train+val_1600_640版本的log吗？

**Comment by exiawsh** [comment]
太长时间了，丢失了。可以给二作发邮件问问

**Comment by loserhou** [comment]
> 太长时间了，丢失了。可以给二作发邮件问问

好的，感谢！

**Comment by yingfei1016** [comment]
[20230411_134824.log](https://github.com/user-attachments/files/16039528/20230411_134824.log)
可能是这个

**Comment by loserhou** [comment]
> [20230411_134824.log](https://github.com/user-attachments/files/16039528/20230411_134824.log) 可能是这个

多谢大佬，祝您工作顺利！

**Comment by wyd-nb** [comment]
> ![2ff08b367077445a0c34d34fc1e9f47](https://github.com/exiawsh/StreamPETR/assets/151776629/1372e31d-9036-4b31-ae83-4bc2b97d7a9e)

想请问下，我也遇到了同样的问题，您当时是如何解决的啊

**Comment by wyd-nb** [comment]
@loserhou 请问您如何解决的nccl报错问题呀？我现在也遇到了同样的问题

**Comment by loserhou** [comment]
直接复制这个问题搜索，我记得csdn有人给了解决问题，祝好运

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2026年02月27日 13:04 |
| 收件人 | exiawsh/StreamPETR ***@***.***> |
| 抄送人 | hou ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [exiawsh/StreamPETR] train+val作为训练集时，多卡训练NCCL超时报错，大佬可以看看吗？ (Issue #212) |
wyd-nb left a comment (exiawsh/StreamPETR#212)

@loserhou 请问您如何解决的nccl报错问题呀？我现在也遇到了同样的问题
