### ISSUE TITLE
Why calculate the value of cls_avg_factor like this?

### ISSUE THREAD

**Issue by xuanzhangyang** [exiawsh/StreamPETR#214]
https://github.com/exiawsh/StreamPETR/blob/95f64702306ccdb7a78889578b2a55b5deb35b2a/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L877

有两个小问题，
1、cls_avg_factor的作用是什么？
2、为什么是这么个计算公式呢？

**Comment by exiawsh** [comment]
您好，这个是petrv2就有的设计。当时我也很疑惑，作者给出的是一个平均概率的解释。外接球体体积的体积=4π/3*(d/2)的3次方。4/3×1/8是1/6

**Comment by xuanzhangyang** [comment]
> 您好，这个是petrv2就有的设计。当时我也很疑惑，作者给出的是一个平均概率的解释。外接球体体积的体积=4π/3*(d/2)的3次方。4/3×1/8是1/6

好的，感谢
