### ISSUE TITLE
请问如何根据输入的图像size和最终的size来设置resize_lim

### ISSUE THREAD

**Issue by SmallXieGithub** [exiawsh/StreamPETR#215]

**Comment by SmallXieGithub** [comment]
我的输入size是 [1200, 1920], final_size [256, 704] 如何设置resize_lim呢？

**Comment by SmallXieGithub** [comment]
如果进一步调整final_size，应该如何调整resize_lim呢

**Comment by exiawsh** [comment]
我们分别进行了resize和crop，crop的幅度需要根据相机安装角度来决定。首先确定resize系数，例如0.4，然后假设高度crop的百分比是0.1，那么final_size可以设置为1200×0.3=360，1920×0.4=768。然后选取一个上下波动的幅度，例如5％。resize_lim设置为（0.4-0.05，0.4+0.05）即可。要注意resize_lim下界要大于等于360/1200。

**Comment by SmallXieGithub** [comment]
非常感谢您的回复
