### ISSUE TITLE
关于Focal-PETR中的注意力图

### ISSUE THREAD

**Issue by flyingdrone** [exiawsh/StreamPETR#216]
作者你好，请问文章中这种注意力图是怎么生成的？是FocalHead文件中的heatmaps吗，还是可以在debug过程中直接导出注意力矩阵？
![image](https://github.com/exiawsh/StreamPETR/assets/88313273/2ee798f6-f904-47c8-970c-b625021e5c7f)

**Comment by exiawsh** [comment]
您好，是debug过程中导出注意力矩阵生成的。
