### ISSUE TITLE
StreamPetr Tracking 

### ISSUE THREAD

**Issue by Gaondong** [exiawsh/StreamPETR#218]
请问streampetr也能有sparse4dv3类似的无需训练的tracking 能力吗？

**Comment by exiawsh** [comment]
我们直接使用的centertrack，根据网络回归的速度进行最近邻匹配。

**Comment by Gaondong** [comment]
> 我们直接使用的centertrack，根据网络回归的速度进行最近邻匹配。

看到您代码中是按照速度来进行匹配的，比较好奇streampetr是不是也具有sparse4dv3类似的跟踪能力，每个query在时空上表示的也是同一目标。

**Comment by exiawsh** [comment]
这个没有尝试过。如果不具备的话，可能跟temporal dn有关系。

**Comment by Gaondong** [comment]
好的 &nbsp;感谢回复



发自我的iPhone


------------------ Original ------------------
From: exiawsh ***@***.***&gt;
Date: Wed,Jul 17,2024 7:52 PM
To: exiawsh/StreamPETR ***@***.***&gt;
Cc: jiandong.gao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [exiawsh/StreamPETR] StreamPetr Tracking  (Issue #218)





 
这个没有尝试过。如果不具备的话，可能跟temporal dn有关系。

**Comment by Gaondong** [comment]
> 这个没有尝试过。如果不具备的话，可能跟temporal dn有关系。

去除denoise, finetune了几个epoch，query本身其实也具有时序上的一致性，近处40米以内也能做到输出同id，主要问题是远处存在一些射线方向冗余误检（threshold=0.2，FP与TP的置信度都在0.2*，无法区分），会导致id跳。

**Comment by nnop** [comment]
@Gaondong 不用temporal denoising也有tracking能力吗？由此看来主要来自于query的temporal propagation？
