### ISSUE TITLE
why all the  ground truth 3dbbox and intrinsics extrinsics   all changed after train_pipeline process？

### ISSUE THREAD

**Issue by lianshushu** [exiawsh/StreamPETR#22]

**Comment by exiawsh** [comment]
Refer to ResizeCropFlipRotImage, GlobalRotScaleTransImage. Because we adopt image and bev augumentation.

**Comment by lianshushu** [comment]
so the params also need to adapt the image size?

**Comment by lianshushu** [comment]
the ground truth 3dbbox  is under lidar coord,why the 3dbbox changed with the image size?

**Comment by exiawsh** [comment]
The 3dbbox do not change with the image size but change with the aug in bird-eye-view (GlobalRotScaleTransImage). You can refer to bevdet for more details.

**Comment by lianshushu** [comment]
I see, thank you!
