### ISSUE TITLE
Velocity frame transformation

### ISSUE THREAD

**Issue by sandropapais** [exiawsh/StreamPETR#225]
In `pre_update_memory()` the variables `memory_egopose` and `memory_reference_point` are transformed to the current reference frame. Why is `memory_velo` also not updated to the current reference frame?

**Comment by exiawsh** [comment]
If the reference point is explicitly operated on, a matrix transformation is required. If it is encoded implicitly, it doesn't matter much, because the transformation matrix is encoded as well.
