### ISSUE TITLE
post_update_memory mechanism

### ISSUE THREAD

**Issue by ETbaty** [exiawsh/StreamPETR#229]
Hi, i was wondering regarding the post_update_memory that is practically based on propagating the topk recent best score queries. 

in the case where the BG is a class of its own, you risk in propagating only (or many) high quality BG queries rather than the best of the FG class. 

did you happen to attend to this question in your studies or found it irrelevant ? from my experience the BG class get prety high score as its rather distinctive so the memory bank is saturated with BG classes

Thanks for your impressive work

**Comment by exiawsh** [comment]
Hi, thanks for your attention!
We use Focal loss. Focal loss only performs binary classification on 10 foreground categories.
The situation you mentioned only appears in CE Loss, where the background is counted as a separate category (10+1 category).

**Comment by ETbaty** [comment]
thanks for clarifying that !
