### ISSUE TITLE
No module named 'flash_attn'

### ISSUE THREAD

**Issue by da-qing-wa** [exiawsh/StreamPETR#23]
Hi, thanks for sharing your wonderful work!
I met a problem when I was trying to run PETRv1 testing using the following code on Tesla V100-PCIE-32GB:
```
tools/dist_test.sh projects/configs/PETRv1/petrv1_r50_flash_704_24e.py ckpts/fcos3d_vovnet_imgbackbone-remapped.pth 4 --eval bbox
```

I have read the docs and a relevant issue, and have changed `type='PETRMultiheadFlashAttention'` in petrv1_r50_flash_704_24e.py line 80 to `type='PETRMultiheadAttention'` , but I still got the following error:
```
ModuleNotFoundError: No module named 'flash_attn'
```

For more detailed infomation:

![image](https://github.com/exiawsh/StreamPETR/assets/80626506/adcf76da-218d-4775-9b63-364328c10b6c)

![image](https://github.com/exiawsh/StreamPETR/assets/80626506/9e0ec87d-ee68-4774-b9a0-a4c373792ca3)

![image](https://github.com/exiawsh/StreamPETR/assets/80626506/30917b3d-fec8-4c90-9cce-c2c373166383)

pip list:
```
Package                  Version      Editable project location
------------------------ ------------ ------------------------------------------------------
absl-py                  1.4.0
addict                   2.4.0
anyio                    3.7.0
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    23.1.0
backcall                 0.2.0
beautifulsoup4           4.12.2
black                    23.3.0
bleach                   6.0.0
cachetools               5.3.1
certifi                  2023.5.7
cffi                     1.15.1
charset-normalizer       3.1.0
click                    8.1.3
colorama                 0.4.6
comm                     0.1.3
contourpy                1.0.7
cycler                   0.11.0
debugpy                  1.6.7
decorator                5.1.1
defusedxml               0.7.1
descartes                1.1.0
einops                   0.6.1
exceptiongroup           1.1.1
executing                1.2.0
fastjsonschema           2.17.1
fire                     0.5.0
flake8                   6.0.0
fonttools                4.39.4
fqdn                     1.5.1
google-auth              2.19.0
google-auth-oauthlib     1.0.0
grpcio                   1.54.2
idna                     3.4
imageio                  2.29.0
importlib-metadata       6.6.0
importlib-resources      5.12.0
iniconfig                2.0.0
ipykernel                6.23.1
ipython                  8.12.2
ipython-genutils         0.2.0
ipywidgets               8.0.6
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.2.0
jupyter-console          6.6.3
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.6.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.7
kiwisolver               1.4.4
llvmlite                 0.36.0
lyft-dataset-sdk         0.0.8
Markdown                 3.4.3
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.5.2
matplotlib-inline        0.1.6
mccabe                   0.7.0
mdurl                    0.1.2
mistune                  2.0.5
mmcls                    0.25.0
mmcv-full                1.6.0
mmdet                    2.28.2
mmdet3d                  1.0.0rc6     /home/q.du/workspace/3d_object_detection/mmdetection3d
mmsegmentation           0.30.0
model-index              0.1.11
mypy-extensions          1.0.0
nbclassic                1.0.0
nbclient                 0.8.0
nbconvert                7.4.0
nbformat                 5.8.0
nest-asyncio             1.5.6
networkx                 2.2
notebook                 6.5.4
notebook_shim            0.2.3
numba                    0.53.0
numpy                    1.23.4
nuscenes-devkit          1.1.10
oauthlib                 3.2.2
opencv-python            4.7.0.72
openmim                  0.3.7
ordered-set              4.1.0
overrides                7.3.1
packaging                23.1
pandas                   2.0.1
pandocfilters            1.5.0
parso                    0.8.3
pathspec                 0.11.1
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.0.1
pkgutil_resolve_name     1.3.10
platformdirs             3.5.1
plotly                   5.14.1
pluggy                   1.0.0
plyfile                  0.9
prettytable              3.7.0
prometheus-client        0.17.0
prompt-toolkit           3.0.38
protobuf                 4.23.2
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pycocotools              2.0.6
pycodestyle              2.10.0
pycparser                2.21
pyflakes                 3.0.1
Pygments                 2.15.1
pyparsing                3.0.9
pyquaternion             0.9.9
pyrsistent               0.19.3
pytest                   7.3.1
python-dateutil          2.8.2
python-json-logger       2.0.7
pytz                     2023.3
PyWavelets               1.4.1
PyYAML                   6.0
pyzmq                    25.1.0
qtconsole                5.4.3
QtPy                     2.3.1
requests                 2.31.0
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.3.5
rsa                      4.9
scikit-image             0.19.3
scikit-learn             1.2.2
scipy                    1.10.1
Send2Trash               1.8.2
setuptools               66.0.0
Shapely                  1.8.5
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.4.1
stack-data               0.6.2
tabulate                 0.9.0
tenacity                 8.2.2
tensorboard              2.13.0
tensorboard-data-server  0.7.0
termcolor                2.3.0
terminado                0.17.1
terminaltables           3.1.10
threadpoolctl            3.1.0
tifffile                 2023.4.12
tinycss2                 1.2.1
tomli                    2.0.1
torch                    1.9.0+cu111
torchaudio               0.9.0
torchvision              0.10.0+cu111
tornado                  6.3.2
tqdm                     4.65.0
traitlets                5.9.0
trimesh                  2.35.39
typing_extensions        4.6.2
tzdata                   2023.3
uri-template             1.2.0
urllib3                  1.26.16
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.5.2
Werkzeug                 2.3.4
wheel                    0.38.4
widgetsnbextension       4.0.7
yapf                     0.33.0
zipp                     3.15.0
```

Any ideas about this problem?

**Comment by exiawsh** [comment]
Hi, thanks for your interest, 
You need to comment out some code:
https://github.com/exiawsh/StreamPETR/blob/74bf34a720d91e29550391e90a2f24c5f13ab1b0/projects/mmdet3d_plugin/models/utils/petr_transformer.py#L29

**Comment by da-qing-wa** [comment]
I have comment out this line, but I found `StreamPETR/mmdetection3d/configs/_base_/datasets/nus-3d.py` doesn't seem to exist.

**Comment by exiawsh** [comment]
> I have comment out this line, but I found `StreamPETR/mmdetection3d/configs/_base_/datasets/nus-3d.py` doesn't seem to exist.

Check your **data folder structure** and the version of mmdet3d.

**Comment by da-qing-wa** [comment]
If I want to specify the path name of the dataset, for example, change the default ./data/nuscenes to ./data/nuscenes-mini, what should I do?

**Comment by exiawsh** [comment]
> If I want to specify the path name of the dataset, for example, change the default ./data/nuscenes to ./data/nuscenes-mini, what should I do?

Change your data folder name, nuscenes-mini -> nuscenes
and build the corresponding pkl files.
StreamPETR
├── data/
│   ├── nuscenes/
│   │   ├── maps/
│   │   ├── samples/
│   │   ├── sweeps/
│   │   ├── v1.0-test/
|   |   ├── v1.0-trainval/
|   |   ├── nuscenes2d_infos_temporal_train.pkl
|   |   ├── nuscenes2d_infos_temporal_val.pkl

**Comment by da-qing-wa** [comment]
Thanks for your advice! The command:
```
tools/dist_test.sh projects/configs/PETRv1/petrv1_r50_flash_704_24e.py ckpts/fcos3d_vovnet_imgbackbone-remapped.pth 1 --eval bbox
```
 can run successfully now.

But the result seems to be incorrect. Is it that I used the wrong model weights? (or some other mistakes I made
![image](https://github.com/exiawsh/StreamPETR/assets/80626506/0b875071-b26b-40c0-9f5f-b297d20cb294)

**Comment by exiawsh** [comment]
> Thanks for your advice! The command:
> 
> ```
> tools/dist_test.sh projects/configs/PETRv1/petrv1_r50_flash_704_24e.py ckpts/fcos3d_vovnet_imgbackbone-remapped.pth 1 --eval bbox
> ```
> 
> can run successfully now.
> 
> But the result seems to be incorrect. Is it that I used the wrong model weights? (or some other mistakes I made ![image](https://user-images.githubusercontent.com/80626506/242288056-0b875071-b26b-40c0-9f5f-b297d20cb294.png)

We have not provided checkpoint of PETRv1.
You can try StreamPETR instead.
Using this config:
 https://github.com/exiawsh/StreamPETR/blob/main/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py
and this checkpoint:
https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth

**Comment by da-qing-wa** [comment]
I tried with the recommended config and checkpoint, this result seems quite good now!

![image](https://github.com/exiawsh/StreamPETR/assets/80626506/aba43359-d5a9-45b8-b631-db7b377c110f)

Now, I'm trying to visualize the result with:
```
python tools/visualize.py
```

and I changed line7,8 in the file to be:
```
result_json = "test/stream_petr_vov_flash_800_bs2_seq_24e/Wed_May_31_09_42_34_2023/pts_bbox/results_nusc"
dataroot='data/nuscenes'
```

An error occurred:
```
Traceback (most recent call last):
  File "tools/visualize.py", line 15, in <module>
    nusc = NuScenes(version='v1.0-trainval', dataroot=dataroot, verbose=True, pred = True, annotations = result_json, score_thr=0.25)
  File "/home/q.du/workspace/3d_object_detection/StreamPETR/tools/visual_nuscenes.py", line 86, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: data/nuscenes/v1.0-trainval
```

And I didn't find such a dirname, too. Here's my data folder structure:
```
.
├── ckpts
├── data
│   └── nuscenes
│       ├── maps
│       ├── samples
│       │   ├── CAM_BACK
│       │   ├── CAM_BACK_LEFT
│       │   ├── CAM_BACK_RIGHT
│       │   ├── CAM_FRONT
│       │   ├── CAM_FRONT_LEFT
│       │   ├── CAM_FRONT_RIGHT
│       │   ├── LIDAR_TOP
│       │   ├── RADAR_BACK_LEFT
│       │   ├── RADAR_BACK_RIGHT
│       │   ├── RADAR_FRONT
│       │   ├── RADAR_FRONT_LEFT
│       │   └── RADAR_FRONT_RIGHT
│       ├── sweeps
│       │   ├── CAM_BACK
│       │   ├── CAM_BACK_LEFT
│       │   ├── CAM_BACK_RIGHT
│       │   ├── CAM_FRONT
│       │   ├── CAM_FRONT_LEFT
│       │   ├── CAM_FRONT_RIGHT
│       │   ├── LIDAR_TOP
│       │   ├── RADAR_BACK_LEFT
│       │   ├── RADAR_BACK_RIGHT
│       │   ├── RADAR_FRONT
│       │   ├── RADAR_FRONT_LEFT
│       │   └── RADAR_FRONT_RIGHT
│       └── v1.0-mini
├── docs
├── figs
├── mmdetection3d -> ../mmdetection3d
├── nusc_tracking
├── projects
│   ├── configs
│   │   ├── PETRv1
│   │   ├── StreamPETR
│   │   └── test_speed
│   └── mmdet3d_plugin
│       ├── core
│       │   ├── apis
│       │   ├── bbox
│       │   └── evaluation
│       ├── datasets
│       │   ├── pipelines
│       │   ├── __pycache__
│       │   └── samplers
│       ├── models
│       │   ├── backbones
│       │   ├── dense_heads
│       │   ├── detectors
│       │   ├── necks
│       │   └── utils
│       └── __pycache__
├── result_vis
├── test
│   └── stream_petr_vov_flash_800_bs2_seq_24e
│       └── Wed_May_31_09_42_34_2023
│           └── pts_bbox
└── tools
    ├── data_converter
    │   └── __pycache__
    └── __pycache__
```

**Comment by exiawsh** [comment]
@da-qing-wa version='v1.0-mini'

**Comment by da-qing-wa** [comment]
It works now. Thank you very much for your patience! :) :)

( ps: looking forward to the release of the checkpoint of PETRv1 :) )

**Comment by jojolee123** [comment]
> @da-qing-wa Hi, thanks for your interest, You need to comment out some code:
> 
> https://github.com/exiawsh/StreamPETR/blob/74bf34a720d91e29550391e90a2f24c5f13ab1b0/projects/mmdet3d_plugin/models/utils/petr_transformer.py#L29

hello, when i comment out this line, The  line78  is not defined
![image](https://github.com/exiawsh/StreamPETR/assets/56385650/7f3703da-b1aa-4a70-a406-586b86e855e3)

**Comment by exiawsh** [comment]
@jojolee123  Have you changed the config of flash attn? 
You should change type='PETRMultiheadFlashAttention' to type='PETRMultiheadAttention'. If you change this config, thr line78 will not be used.

**Comment by jojolee123** [comment]
Thank you very much! I still have a few questions I'd like to ask you：
    I have been reading StreamPETR these days, thank you for your nice work! I want to use StreamPETR to do object detection of 2D in automatic driving scene, but it is also a video, which requires the use of temporal modeling. Can you give me some suggestions on how we can use our own dataset and change the network model to adapt to our task (ego transform、input and output)?

**Comment by exiawsh** [comment]
> Thank you very much! I still have a few questions I'd like to ask you：
> I have been reading StreamPETR these days, thank you for your nice work! I want to use StreamPETR to do object detection of 2D in automatic driving scene, but it is also a video, which requires the use of temporal modeling. Can you give me some suggestions on how we can use our own dataset and change the network model to adapt to our task (ego transform、input and output)?

It's difficult to adapt StreamPETR to 2d video object detection…But I can provide you another choice, you can refer to this paper: QueryProp: "QueryProp: Object Query Propagation for High-Performance Video Object Detection".

**Comment by jojolee123** [comment]
I'm sorry that there is a little problem with my expression. Specifically, we need to detect events (including objects and action) of every frame in the video, so temporal information is needed. I think StreamPETR is very good at temporal modeling and object detection in automatic driving scenarios, which is my idea. Can you tell me why you think it's difficult to adapt StreamPETR to 2d video object detection? In addition, I will read the paper you recommended, Thank you again!

**Comment by exiawsh** [comment]
> I'm sorry that there is a little problem with my expression. Specifically, we need to detect events (including objects and action) of every frame in the video, so temporal information is needed. I think StreamPETR is very good at temporal modeling and object detection in automatic driving scenarios, which is my idea. Can you tell me why you think it's difficult to adapt StreamPETR to 2d video object detection? In addition, I will read the paper you recommended, Thank you again!

The idea of temporal modeling through object query is general indeed. But some settings of PETR are designed to 3d detection, it's difficult to tell you which part is important for you scenes. So I recommand you to read QueryProp, which is easier to adapt to your scenes. If you want to use StreamPETR, you have to do lots of ablation study...

**Comment by SMSajadi99** [comment]
> > Thanks for your advice! The command:
> > ```
> > tools/dist_test.sh projects/configs/PETRv1/petrv1_r50_flash_704_24e.py ckpts/fcos3d_vovnet_imgbackbone-remapped.pth 1 --eval bbox
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can run successfully now.
> > But the result seems to be incorrect. Is it that I used the wrong model weights? (or some other mistakes I made ![image](https://user-images.githubusercontent.com/80626506/242288056-0b875071-b26b-40c0-9f5f-b297d20cb294.png)
> 
> We have not provided checkpoint of PETRv1. You can try StreamPETR instead. Using this config: https://github.com/exiawsh/StreamPETR/blob/main/projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py and this checkpoint: https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth

I'm using this command:
`tools/dist_test.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py  work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/latest.pth 1 --eval bbox`

But test result (for 20000 itretion):
![image](https://github.com/exiawsh/StreamPETR/assets/69210109/b941fc43-54ba-4188-8e52-3c9c9619f52f)
