### ISSUE TITLE
Questions about queue_length in stream training and prev_exists flag ?

### ISSUE THREAD

**Issue by happygds** [exiawsh/StreamPETR#24]
1) Hi, after reading the code implementation, I'm curious about why you set `queue_length = 1`  in your config when you used stream training. Wouldn't the performance be better if your increase queue_length ?
2) If the queue_length is set to 1, what's is the difference between prev_exists flag is True or False ?

**Comment by exiawsh** [comment]
@happygds, thanks for your interest.
1. queue_length = 1 is useless when apply stream training. It's used in sliding window training.
In stream training, the queue length is decided by https://github.com/exiawsh/StreamPETR/blob/cdcec00a74034d60c425bbb2076daac615dfcdda/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py#L215
That's mean in stream training, the queue length = 20 = 40 (num_samples per scens) / 2 (seq_split_num).

**Comment by happygds** [comment]
> @happygds, thanks for your interest.
> 
> 1. queue_length = 1 is useless when applying stream training. It's used in sliding window training.
>    In stream training, the queue length is decided by https://github.com/exiawsh/StreamPETR/blob/cdcec00a74034d60c425bbb2076daac615dfcdda/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py#L215
>    
>    That's mean in stream training, the queue length = 20 = 40 (num_samples per scenes) / 2 (seq_split_num).

Thanks, I can understand the effect of `seq_split_num`. However, when I set breakpoint in `detectors/petr3d.py`, the print-info of `data['img'].size()` is `[batch_size, 1, 6, 3, 256, 704]`. 
 -- The queue length is 1, not 20. This means the training input sample is just one timestamp, not the sequence of 20 timestamps.

**Comment by exiawsh** [comment]
@happygds 
The queue length is 1, not 20. This is right case for stream training.
Because we reuse the query features **from last few iterations**.

**Comment by happygds** [comment]
> @happygds The queue length is 1, not 20. This is right case for stream training. Because we reuse the query features **from last few iterations**.

The the memorized query features from last few iterations are almost not from the same sequence. Is this the reason why the model convergence is difficult ?  
 -- How about change the data sampling strategy , for example, sampling continuous frames from one sequence in some neighboring iterations?

**Comment by exiawsh** [comment]
@happygds 
The prev_exists flag and https://github.com/exiawsh/StreamPETR/blob/cdcec00a74034d60c425bbb2076daac615dfcdda/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py#L228 has done it.
We have already sampled continuous frames from one sequence in the neighboring iterations for the same GPU device.

**Comment by happygds** [comment]
Thanks a lot! I didn't notice that !

> @happygds The prev_exists flag and
> 
> https://github.com/exiawsh/StreamPETR/blob/cdcec00a74034d60c425bbb2076daac615dfcdda/projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py#L228
> 
> has done it.
> We have already sampled continuous frames from one sequence in the neighboring iterations for the same GPU device.

Great, thanks a lot, I didn't notice that before !

**Comment by exiawsh** [comment]
@happygds Sorry for the delayed reply. Because I am familiar with PETR,  so I adopted the form of global attention. Deformable attention can also work well, you can refer this paper (https://arxiv.org/abs/2305.14018), which follows the temporal modeling of StreamPETR.
