### ISSUE TITLE
data preparation question

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#25]
Hi i have some questions towards data preparation

1. Do I need to create a folder called data and manually put everything in that folder like the structure you showed us ?
2. How can I creating infos file, where should I execute the command python tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0 ?

**Comment by exiawsh** [comment]
> Hi i have some questions towards data preparation
> 
>     1. Do I need to create a folder called data and manually put everything in that folder like the structure you showed us ?
> 
>     2. How can I creating infos file, where should I execute the command python tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0 ?

1. Yes, you should keep the data structure as the same with as. You can use soft link.
2. You should execute the command under StreamPETR/.
3. If you have difficulty generating pkl files, I can provide a link to Baidu Netdisk if you need it.

**Comment by changliucoding** [comment]
> > Hi i have some questions towards data preparation
> > ```
> > 1. Do I need to create a folder called data and manually put everything in that folder like the structure you showed us ?
> > 
> > 2. How can I creating infos file, where should I execute the command python tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0 ?
> > ```
> 
> 1. Yes, you should keep the data structure as the same with as. You can use soft link.
> 2. You should execute the command under StreamPETR/.
> 3. If you have difficulty generating pkl files, I can provide a link to Baidu Netdisk if you need it.

Hi many thanks for this quick respond. I am still downloading the dataset from nuscense, so if I stuck generate pkl I will come back here again :).

Btw: in your environment setup you first clone mmdetection3d and cd in it and then clone streampetr. But actually mmdetection3d should be in folder streampetr as the structure you showed.

**Comment by exiawsh** [comment]
> > > Hi i have some questions towards data preparation
> > > ```
> > > 1. Do I need to create a folder called data and manually put everything in that folder like the structure you showed us ?
> > > 
> > > 2. How can I creating infos file, where should I execute the command python tools/create_data_nusc.py --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes2d --version v1.0 ?
> > > ```
> > 
> > 
> > 
> > 1. Yes, you should keep the data structure as the same with as. You can use soft link.
> > 2. You should execute the command under StreamPETR/.
> > 3. If you have difficulty generating pkl files, I can provide a link to Baidu Netdisk if you need it.
> 
> Hi many thanks for this quick respond. I am still downloading the dataset from nuscense, so if I stuck generate pkl I will come back here again :).
> 
> Btw: in your environment setup you first clone mmdetection3d and cd in it and then clone streampetr. But actually mmdetection3d should be in folder streampetr as the structure you showed.

Thanks for kind reminding.
I will fix it!
