### ISSUE TITLE
dataset preparation question

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#26]
Hi, I found that nuscenes web has many different versions of map and data. Which one should I download? Also I wonder what should I put in sweep and samples folder?

![_20230604135140](https://github.com/exiawsh/StreamPETR/assets/133587429/54abffd1-a64e-43a4-8055-504166db7764)
 
Thanks!

**Comment by exiawsh** [comment]
You should download and unzip all data in Trainval. After unzip the data, you can find the sample and sweep data. Actually, sweep data is not necessary. You can also download Mini data to have a look, which has the same data structure with trainval, but fewer scenes.

**Comment by changliucoding** [comment]
> You should download and unzip all data in Trainval. After unzip the data, you can find the sample and sweep data. Actually, sweep data is not necessary. You can also download Mini data to have a look, which has the same data structure with trainval, but fewer scenes.

Many thanks!
