### ISSUE TITLE
请问下tracking相关模块预计什么时候释放？

### ISSUE THREAD

**Issue by zzdang** [exiawsh/StreamPETR#3]
您好，请问下tracking相关模块预计什么时候释放？

**Comment by exiawsh** [comment]
We plan to conduct end-to-end MOT based on PF-Track (https://github.com/TRI-ML/PF-Track), while simply replacing PETR with StreamPETR did not significantly improve the performance, so the open-source of MOT code has become a long-term plan. Sorry for that. 

If you are interested in the results on the nuScenes leaderboard, we built it based on Q-Track, but we do not have permission to open source the relevant code (because the author of Q-Track is not from the StreamPETR team). Within a month, we will open source the JSON file for detecting results on nuScenes test set (63.0++ NDS ). Based on this detection result, you can use existing trackers (such as ByteTrack v2) to achieve SOTA results.

**Comment by VisonSpace** [comment]
@exiawsh 交流 qq 2584516776

**Comment by exiawsh** [comment]
> 您好，请问下tracking相关模块预计什么时候释放？

Tracking based on centerpoint implementation released.

**Comment by jianingwangind** [comment]
Hi @exiawsh, would you mind to share some of  your ideas regardign to conduct e2e mot based on PF-Track?

**Comment by exiawsh** [comment]
> Hi @exiawsh, would you mind to briefly share some of your general ideas regarding to conduct e2e mot based on PF-Track?

Hi, thanks for your interest.
In fact, the extension of PF-Track on StreamPETR has already been handled by others. I can only provide some preliminary experience based on our early attempts.
1. When combined StreamPETR with PF-Track, the detection performance of StreamPETR droped a lot. (I think this is one of the main reasons why AMOTA has not improved.)
2. We haven't tried stream training on e2e mot models and conducted sliding window training on PF-Track + StreamPETR, which requires huge GPU Memory and long training time. It's necessart to verfy the feasibility of streaming training on downstream tasks.
You can add my wechat: kira1027293308

**Comment by jianingwangind** [comment]
Thanks a lot for you detailed reply.

**Comment by exiawsh** [comment]
@JunqiaoLi 
Sorry, we have no resources to conduct an extension of PF-Track.

**Comment by Jacky-gsq** [comment]
> > Hi @exiawsh, would you mind to briefly share some of your general ideas regarding to conduct e2e mot based on PF-Track?
> 
> Hi, thanks for your interest. In fact, the extension of PF-Track on StreamPETR has already been handled by others. I can only provide some preliminary experience based on our early attempts.
> 
> 1. When combined StreamPETR with PF-Track, the detection performance of StreamPETR droped a lot. (I think this is one of the main reasons why AMOTA has not improved.)
> 2. We haven't tried stream training on e2e mot models and conducted sliding window training on PF-Track + StreamPETR, which requires huge GPU Memory and long training time. It's necessart to verfy the feasibility of streaming training on downstream tasks.
>    You can add my wechat: kira1027293308

Hi,  as mentioned in "When combined StreamPETR with PF-Track, the detection performance of StreamPETR droped a lot. (I think this is one of the main reasons why AMOTA has not improved."， is there some experimental analycis about the above reason? Or if it's convenient, could I add your wechat and discuss about that? Thanks again!

**Comment by exiawsh** [comment]
@Jacky-gsq I'm sorry. I have no time for designing end-to-end trackingnow, you can try waiting for sparse4d v3.

**Comment by Jacky-gsq** [comment]
@exiawsh OK, Thank you very much! The streampetr is  really a great work and helps us a lot!
