### ISSUE TITLE
Can not reproduce the results of R50 nuimage config.

### ISSUE THREAD

**Issue by AlmoonYsl** [exiawsh/StreamPETR#30]
I used 8*V100 to train the ```stream_petr_r50_flash_704_bs2_seq_428q_nui_60e``` config, but I got the worse performance than the repo.
53.45 NDS, 43.4 mAP

When I used the SyncBN and set ```requires_grad=True, norm_eval=False```, I got even worse results. :sob:
53.07 NDS, 43.03 mAP

BTW, I didn't change anything in the config while I was not using SyncBN.

**Comment by exiawsh** [comment]
> 

You can try requires_grad=False, norm_eval=False.
And I did observe the reproducibility issue of this model. I'm sorry for that, if you want a fair academic comparison, I recommend using a vov or r50-1k model.

**Comment by exiawsh** [comment]
I will check it.

**Comment by AlmoonYsl** [comment]
> @AlmoonYsl You can use requires_grad=False, norm_eval=False. And I did observe the reproducibility issue of this model. I'm sorry for that, if you want a fair academic comparison, I recommend using a vov or r50-1k model.

Thanks for your replay.
I will try it.

**Comment by exiawsh** [comment]
> > I will check it.
> 
> Thanks. Hope you can find the reason. 

But your results are obviously lower than ours. I think that about 44.2 mAP is acceptable.

**Comment by AlmoonYsl** [comment]
> > > I will check it.
> > 
> > 
> > Thanks. Hope you can find the reason.
> 
> But your results are obviously lower than ours. I think that about 44.2 mAP is acceptable.

Yes, it is. I will try SyncBN and set ```requires_grad=False, norm_eval=True```.

**Comment by exiawsh** [comment]
@AlmoonYsl  I have retrained the model, and I got this results:
 pts_bbox_NuScenes/NDS: 0.5405, pts_bbox_NuScenes/mAP: 0.4391
It was indeed little than my previous version.
This may be caused by the filter_empty_gt flag.
In the initial version, I set filter_empty_gt = True, but it has some error, when you want to train on the val set. So I changed it to False. I will check this again.

**Comment by AlmoonYsl** [comment]
> @AlmoonYsl I have retrained the model, and I got this results: pts_bbox_NuScenes/NDS: 0.5405, pts_bbox_NuScenes/mAP: 0.4391 It was indeed little than my previous version. This may be caused by the filter_empty_gt flag. In the initial version, I set filter_empty_gt = True, but it has some error, when you want to train on the val set. So I changed it to False. I will check this again.

Thanks for your replay.
I think the filter_empty_gt flag is necessary for training. Hope you can find the reason, looking forward to your reply!

**Comment by happygds** [comment]
> > > I will check it.
> > 
> > 
> > Thanks. Hope you can find the reason.
> 
> But your results are obviously lower than ours. I think that about 44.2 mAP is acceptable.

 I reproduce the results of R50 nuimage config three times, the mAP is about 44.2/43.9/44.0.

**Comment by LiewFeng** [comment]
> @AlmoonYsl I have retrained the model, and I got this results: pts_bbox_NuScenes/NDS: 0.5405, pts_bbox_NuScenes/mAP: 0.4391 It was indeed little than my previous version. This may be caused by the filter_empty_gt flag. In the initial version, I set filter_empty_gt = True, but it has some error, when you want to train on the val set. So I changed it to False. I will check this again.

Hi, @exiawsh , any updates about this? Does the filter_empty_gt flag lead to the performance drop?
