### ISSUE TITLE
How to change multi-GPU training to single GPU training

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#31]
I noticed that this amazing project uses 8 GPU for training in setting, and I would like to ask how to conduct a preliminary training if I only have one GPU

**Comment by exiawsh** [comment]
> I noticed that this amazing project uses 8 GPU for training in setting, and I would like to ask how to conduct a preliminary training if I only have one GPU

It requires long time and have difficulty for convergence. What's your gpu device and memory?

**Comment by changliucoding** [comment]
> > I noticed that this amazing project uses 8 GPU for training in setting, and I would like to ask how to conduct a preliminary training if I only have one GPU
> 
> It requires long time and have difficulty for convergence. What's your gpu device and memory?

Hi! I am using 4060 8G gpu with 32G ram. I want to test first on my laptop then move to the server to run this. I wonder if this is possible, I found it's hard to change to train from multi-gpu to single-gpu.

**Comment by exiawsh** [comment]
@changliucoding  If you want debug our project, you can use ipdb. If you just want to know the command for single gpu training, you can use tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 1
