### ISSUE TITLE
Checkpoint of PETRv1?

### ISSUE THREAD

**Issue by da-qing-wa** [exiawsh/StreamPETR#32]
Hi,
Could you please provide a checkpoint of PETRv1?
Really need that! Thanks! 
(Since the env of StreamPETR is much easier to setup than the original PETR, as the author of PETR mentioned many times in the issues under PETR)

**Comment by exiawsh** [comment]
> Hi,
> Could you please provide a checkpoint of PETRv1?
> Really need that! Thanks!
> (Since the env of StreamPETR is much easier to setup than the original PETR, as the author of PETR mentioned many times in the issues under PETR)

I will provide the checkpoint tomorrow.

**Comment by da-qing-wa** [comment]
> I will provide the checkpoint tomorrow.

Nice! Looking forward!

**Comment by exiawsh** [comment]
@da-qing-wa 
Please check. 
https://github.com/exiawsh/storage/releases/download/v1.0/petrv1_r50_flash_704_24e.pth
I use SyncBN, so the performance is better.
norm_cfg=dict(type='SyncBN', requires_grad=False),
norm_eval=False,

**Comment by da-qing-wa** [comment]
> norm_cfg=dict(type='SyncBN', requires_grad=False),
> norm_eval=False,

Thanks! I have tried it. The result is similar to this.

**Comment by da-qing-wa** [comment]
> @da-qing-wa Please check. https://github.com/exiawsh/storage/releases/download/v1.0/petrv1_r50_flash_704_24e.pth I use SyncBN, so the performance is better. norm_cfg=dict(type='SyncBN', requires_grad=False), norm_eval=False,
> 
> Evaluating bboxes of pts_bbox mAP: 0.3076 mATE: 0.7587 mASE: 0.2838 mAOE: 0.6625 mAVE: 1.0634 mAAE: 0.3375 NDS: 0.3495 Eval time: 175.7s
> 
> Per-class results: Object Class AP ATE ASE AOE AVE AAE car 0.512 0.570 0.155 0.117 1.443 0.314 truck 0.236 0.789 0.234 0.238 1.296 0.328 bus 0.303 0.858 0.226 0.179 2.152 0.467 trailer 0.083 1.169 0.243 0.569 0.513 0.101 construction_vehicle 0.043 0.937 0.495 1.140 0.121 0.384 pedestrian 0.364 0.745 0.304 1.383 0.894 0.613 motorcycle 0.299 0.722 0.274 0.978 1.511 0.377 bicycle 0.256 0.616 0.286 1.206 0.577 0.116 traffic_cone 0.530 0.528 0.334 nan nan nan barrier 0.449 0.654 0.287 0.153 nan nan 2023-06-18 13:26:48,141 - mmdet - INFO - Exp name: petrv1_r50_flash_704_24e.py

Thanks! I have tried it. The result is similar to this.
