### ISSUE TITLE
How about the performance with Streaming Video Training.

### ISSUE THREAD

**Issue by zehuichen123** [exiawsh/StreamPETR#36]
Hi, thanks for your great work. I wonder about the performance of streaming video training. Does it achieve the same mAP/NDS as the random shuffle one?

**Comment by exiawsh** [comment]
@zehuichen123  For 3D object detection on nuScenes, the streaming video training can achieve the same mAP/NDS as the random shuffle one, if you train the temporal model with dn or dense depth supervision with more than 60 epochs. But the performance will drop, if you train the single frame model. The performance also drops when you train other tasks (e.g. online hd map construction). You should increase the diversity of sampler.

**Comment by zehuichen123** [comment]
Thanks for your suggestions!
