### ISSUE TITLE
dataset queue length conflict 

### ISSUE THREAD

**Issue by fengye1966** [exiawsh/StreamPETR#37]
Hi, Thank you for your sharing in the first place. I was using the default streaming config with queue length = 1. and over here when preparing the samples,

[https://github.com/exiawsh/StreamPETR/blob/1111ffaa685068059fb112e58c6c4bb9d9c418f6/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py#L91](url)
 
random length is 0 by default, and queue_length equals  to 1 and index_list will only contains one sample in the end but generally it should contains two samples since it was used at here later on
[https://github.com/exiawsh/StreamPETR/blob/1111ffaa685068059fb112e58c6c4bb9d9c418f6/projects/mmdet3d_plugin/models/detectors/petr3d.py#L255](url)

 Could you please point out where am I wrong about this? do we need 2 samples each iter all the time? since I saw there's one example of [batchsize, 1, 6, 3, h, w] in the issues before. Thank you!

**Comment by exiawsh** [comment]
@fengye1966 When you use streaming config, the queue length and random length are useless. prev_img is also not used in stream training. They are used in sliding window training.

**Comment by fengye1966** [comment]
> 

Thank you for your fast response. So basically in streaming mode, the dataloader prepared 20 (40 / 2) continuous samples ahead and we're using one image input at a single iteration. is that correct?

**Comment by exiawsh** [comment]
@fengye1966 Yes, you are right.
