### ISSUE TITLE
about TensorRT inference

### ISSUE THREAD

**Issue by kangxiao18** [exiawsh/StreamPETR#39]
Hi, I see you list "TensorRT inference" on the checklist, are you still working on the TensorRT inference? I'm trying to use mmdeploy on this project but things not go well. Do you have some suggestions about it? 
Btw, when will this function updated on this project? Thank you.

**Comment by exiawsh** [comment]
@kangxiao18 Hi, I'm sorry. I'm busy with other things. But you can refer to this open source project, which has converted our project to onnx. https://github.com/woquyuna/StreamPETR/blob/deployV1.0/docs/deploy.md

**Comment by kangxiao18** [comment]
> @kangxiao18 Hi, I'm sorry. I'm busy with other things. But you can refer to this open source project, which has converted our project to onnx. https://github.com/woquyuna/StreamPETR/blob/deployV1.0/docs/deploy.md

Thank you for your quickly reply. I will try it.
