### ISSUE TITLE
Still about TensorRT inference

### ISSUE THREAD

**Issue by kangxiao18** [exiawsh/StreamPETR#40]
@exiawsh Hi, thank you for your suggestion last time. After that, I have tried with https://github.com/woquyuna/StreamPETR/blob/deployV1.0/docs/deploy.md, but fialed at last.
Two problems happened here.
1. I tried to run this command: `tools/dist_test_pth.sh projects/configs/StreamPETR/stream_petr_r50_704_bs2_seq_428q_nui_60e_pth.py ckpts/stream_petr_r50_flash_704_bs2_seq_428q_nui_60e.pth 1 --eval=bbox`
, and it reported with this error:
![image](https://github.com/exiawsh/StreamPETR/assets/5684798/baccf9a3-17f0-4969-970c-bf4862744b2f)
Is it because stream_petr_r50_704_bs2_seq_428q_nui_60e_pth.py differing from stream_petr_r50_flash_704_bs2_seq_428q_nui_60e.pth and this author had another pth file. So I try to train with stream_petr_r50_flash_704_bs2_seq_428q_nui_60e.pth config file.
2. `tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_704_bs2_seq_428q_nui_60e_pth.py 8 --work-dir work_dirs/stream_petr_r50_704_bs2_seq_428q_nui_60e/`
Then I run this command, and it report with this error:
![image](https://github.com/exiawsh/StreamPETR/assets/5684798/166288e6-fcd8-47a1-be2f-f3716a9f8774)
It seems that this author had changed something with models/dense_heads/streampetr_head_pth.py or petr3d_pth

P.S.: I tried to run this training command: "tools/dist_train.sh projects/configs/StreamPETR/stream_petr_r50_flash_704_bs2_seq_24e.py 8 --work-dir work_dirs/stream_petr_r50_flash_704_bs2_seq_24e/", and it runs well.

**Comment by exiawsh** [comment]
@kangxiao18 I'm sorry for that. I haven't tried this, I may provide the tensorrt version in Novemeber.

**Comment by kangxiao18** [comment]
> @kangxiao18 I'm sorry for that. I haven't tried this, I may provide the tensorrt version in Novemeber.

Still, thank you for your reply.
