### ISSUE TITLE
Problem with data preparation （关于数据准备的问题）

### ISSUE THREAD

**Issue by MalignusCN** [exiawsh/StreamPETR#41]
Hi, I've found that our project's data preparation is different from others. The problem is if I creates 2D annotations and temporal information follow data_preparatio.md in our project, will it effect other projects like BEVDet, SOLOFusion which use the same data root(nuscenes).
Thank you.

作者你好，我发现我们的data preparation和现有的工作不太一致，我想问下，如果按照我们的pipeline对nuscenes数据集进行了处理，对于我其他使用nuscnenes数据集的project（例如BEVDet，SOLOFusion那些完全follow mmdet3d）的工作是否会有影响？谢谢

**Comment by exiawsh** [comment]
@MalignusCN I'm not very sure. The pkl files are compatible with mmdet3d 1.0. While the bevdet and solofusion seems to have other processing information.

**Comment by MalignusCN** [comment]
> @MalignusCN I'm not very sure. The pkl files are compatible with mmdet3d 1.0. While the bevdet and solofusion seems to have other processing information.

Okay, I will try it and update the progress. Thank you.

**Comment by fengye1966** [comment]
> Hi, I've found that our project's data preparation is different from others. The problem is if I creates 2D annotations and temporal information follow data_preparatio.md in our project, will it effect other projects like BEVDet, SOLOFusion which use the same data root(nuscenes). Thank you.
> 
> 作者你好，我发现我们的data preparation和现有的工作不太一致，我想问下，如果按照我们的pipeline对nuscenes数据集进行了处理，对于我其他使用nuscnenes数据集的project（例如BEVDet，SOLOFusion那些完全follow mmdet3d）的工作是否会有影响？谢谢

streampetr会单独生成一份他需要的数据集，对你其他的没影响，不会修改你其他的数据集文件

**Comment by MalignusCN** [comment]
> > Hi, I've found that our project's data preparation is different from others. The problem is if I creates 2D annotations and temporal information follow data_preparatio.md in our project, will it effect other projects like BEVDet, SOLOFusion which use the same data root(nuscenes). Thank you.
> > 作者你好，我发现我们的data preparation和现有的工作不太一致，我想问下，如果按照我们的pipeline对nuscenes数据集进行了处理，对于我其他使用nuscnenes数据集的project（例如BEVDet，SOLOFusion那些完全follow mmdet3d）的工作是否会有影响？谢谢
> 
> streampetr会单独生成一份他需要的数据集，对你其他的没影响，不会修改你其他的数据集文件

Thank you
