### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by MalignusCN** [exiawsh/StreamPETR#43]
Hi exiawsh,  

Here is a small bug, all configs provided in "projects/configs/StreamPETR/*.py", the val&test of data config didn't clarified the data_root, only train clarified. Maybe you can fixed this bug in the next version~

**Comment by exiawsh** [comment]
> Hi exiawsh,
> 
> Here is a small bug, all configs provided in "projects/configs/StreamPETR/*.py", the val&test of data config didn't clarified the data_root, only train clarified. Maybe you can fixed this bug in the next version~

Thank you! I will fix it.
