### ISSUE TITLE
question about tracking

### ISSUE THREAD

**Issue by JunqiaoLi** [exiawsh/StreamPETR#45]
First, thank for your great work.
However, I have a question about tracking, you have mentioned to use 
'python nusc_tracking/pub_test --version v1.0-trainval --checkpoint {PATH_RESULTS.JSON} --data_root {PATH_NUSCENES}' 
to evaluate the tracking. 
Could you plz tell me how to get the {PATH_RESULTS.JSON}?

**Comment by exiawsh** [comment]
> First, thank for your great work. However, I have a question about tracking, you have mentioned to use 'python nusc_tracking/pub_test --version v1.0-trainval --checkpoint {PATH_RESULTS.JSON} --data_root {PATH_NUSCENES}' to evaluate the tracking. Could you plz tell me how to get the {PATH_RESULTS.JSON}?

Evaluation the detection model. And you can obtain the json file undet test folder.

**Comment by JunqiaoLi** [comment]
> > First, thank for your great work. However, I have a question about tracking, you have mentioned to use 'python nusc_tracking/pub_test --version v1.0-trainval --checkpoint {PATH_RESULTS.JSON} --data_root {PATH_NUSCENES}' to evaluate the tracking. Could you plz tell me how to get the {PATH_RESULTS.JSON}?
> 
> Evaluation the detection model. And you can obtain the json file undet test folder.

Thank for your quick reply!
But in the test.py https://github.com/exiawsh/StreamPETR/blob/main/tools/test.py#L240, you didn't dump it since it is a list, whose item is a dict and the key is ['pts_bbox']. So I cannot get the result json file.

Am I misunderstanding it?

**Comment by exiawsh** [comment]
> > > First, thank for your great work. However, I have a question about tracking, you have mentioned to use 'python nusc_tracking/pub_test --version v1.0-trainval --checkpoint {PATH_RESULTS.JSON} --data_root {PATH_NUSCENES}' to evaluate the tracking. Could you plz tell me how to get the {PATH_RESULTS.JSON}?
> > 
> > 
> > Evaluation the detection model. And you can obtain the json file undet test folder.
> 
> Thank for your quick reply! But in the test.py https://github.com/exiawsh/StreamPETR/blob/main/tools/test.py#L240, you didn't dump it since it is a list, whose item is a dict and the key is ['pts_bbox']. So I cannot get the result json file.
> 
> Am I misunderstanding it?

The saving of json filesvis in nuScnenes Dataset in mmdet3d.

**Comment by JunqiaoLi** [comment]
OK, got it.
Thank you so muck!
