### ISSUE TITLE
Does cls_branches/reg_branches  share the weights?

### ISSUE THREAD

**Issue by dop0** [exiawsh/StreamPETR#46]
Hello, from the denfinition, cls  branches  seems share the weights with fc_cls, but in forward function,  `outputs_class = self.cls_branches[lvl](outs_dec[lvl])`, which looks like every decoders' output intends to use different classifier.
https://github.com/exiawsh/StreamPETR/blob/1111ffaa685068059fb112e58c6c4bb9d9c418f6/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L254-L257

Whether cls branchs ModuleList shares the weights or not? And will they differ in metrics? Thank you.

**Comment by exiawsh** [comment]
@dop0 They share the same weights. We follow the implementation of detr and deformable detr. If you conduct iterative refine, you should use deepcopy, which uses different weights for different decoder layers.

**Comment by dop0** [comment]
Ok, I know the reason. Thank you for quick reply!
