### ISSUE TITLE
3D photo target coordinates

### ISSUE THREAD

**Issue by SMSajadi99** [exiawsh/StreamPETR#48]
Hello again
Thank you very much for the previous tips
I got the final result.
I'm going to give it a picture and give me the 3D box with the coordinates, what should I do?

**Comment by SMSajadi99** [comment]
https://github.com/exiawsh/StreamPETR/blob/main/docs/training_inference.md#visualize
I checked this case, but it doesn't answer on Kolb because it wants to access which it doesn't allow.

**Comment by exiawsh** [comment]
> https://github.com/exiawsh/StreamPETR/blob/main/docs/training_inference.md#visualize
> I checked this case, but it doesn't answer on colab because it wants to access which it doesn't allow.

I haven't used colab for visualizations, you can download json files locally and visualize them. Visualization does not need high demands on the gpu.

**Comment by SMSajadi99** [comment]
`./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --format-only`
Can I do this with this command?
