### ISSUE TITLE
Result mAP

### ISSUE THREAD

**Issue by SMSajadi99** [exiawsh/StreamPETR#50]
Hi, I hope you are well
According to https://github.com/exiawsh/StreamPETR/issues/23#issuecomment-1626910379 I did 20,000 iterations but the results were not good and it didn't work at all! What should I do? (because I want it to be based on my own training)

**Comment by exiawsh** [comment]
It seems that you only use the data in mini dataset for training. You should use the data on the whole dataset.

**Comment by SMSajadi99** [comment]
I don't know about this issue, is it possible to optimize this issue to get results?
I had another question, can I do all the next steps with the checkpoints you gave me?
Because in step `./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --format-only` we have to execute the following code that points to the folder that was created in the training step, should we change it to the given checkpoints?

**Comment by exiawsh** [comment]
> I don't know about this issue, is it possible to optimize this issue to get results? I had another question, can I do all the next steps with the checkpoints you gave me? Because in step `./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --format-only` we have to execute the following code that points to the folder that was created in the training step, should we change it to the given checkpoints?

Yes. You should change it to the given checkpoints.

**Comment by SMSajadi99** [comment]
Great, thanks so much
