### ISSUE TITLE
Some questions about MLN

### ISSUE THREAD

**Issue by mingyangShang** [exiawsh/StreamPETR#52]
I have some questions about MLN, could you please help to solve these?
1) Why MLN is designed in formulation of affine transformation? Is there some theorical insights, did you try other ways like concat?
2) MLN takes velocity as input, but i didn't find the explanation about how it is obtained, could you show me out (if i missed it)?

**Comment by jjlinghu** [comment]
Hi, thank you for this excellent work ! I also have a question about MLN. Looking forward to your answer please!
Here we use MLN for **tgt**, I wonder know it is necessary to use the `rec_ego_motion`  without history information to guide tgt via conditional normalization method. Why we choose the more abundant `memory_ego_motion` to deal with the **tgt** ?
https://github.com/exiawsh/StreamPETR/blob/11ed0dc19b1852500ab3c7d2e6a0df237f6e28b8/projects/mmdet3d_plugin/models/dense_heads/streampetr_head.py#L431

**Comment by exiawsh** [comment]
Hi.
It's not necessary to use MLN for the zeros init tgt.
