### ISSUE TITLE
Some questions about the result on Nuscenes test set

### ISSUE THREAD

**Issue by jjlinghu** [exiawsh/StreamPETR#53]
Thanks for your great work!
I retrained the model according  to  the modification as you mentioned in #34 . And I get the performance too high to believe it is credible. 
**Evaluating bboxes of pts_bbox
mAP: 0.8604
mATE: 0.2689
mASE: 0.1917
mAOE: 0.0826
mAVE: 0.1514
mAAE: 0.2030
NDS: 0.8404
Eval time: 130.2s**
Then I replaced `nuscenes2d_temporal_infos_val.pkl` with `nuscenes2d_temporal_infos_test.pkl` in `data=dict(...,test =dict(...),)`, but some error occurred.
![image](https://github.com/exiawsh/StreamPETR/assets/54942065/c97d013c-d839-4179-b1f0-e38d30a01c54)
How can I deal with it please.

**Comment by yingfei1016** [comment]
Hi，
    The result has over-fitted on the val set, so this result is normal.
    To get the result on test set, you need to use "--format-only" instead of "--eval bbox". For example, 
```./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --format-only```
    After that you can get the json files of test results. You can upload it to https://eval.ai/web/challenges/challenge-page/356/submission .

**Comment by jjlinghu** [comment]
> Hi， The result has over-fitted on the val set, so this result is normal. To get the result on test set, you need to use "--format-only" instead of "--eval bbox". For example, `./tools/dist_test.sh projects/configs/StreamPETR/stream_petr_vov_flash_800_bs2_seq_24e.py work_dirs/stream_petr_vov_flash_800_bs2_seq_24e/latest.pth 8 --format-only` After that you can get the json files of test results. You can upload it to https://eval.ai/web/challenges/challenge-page/356/submission .

It's helpful for me, thanks for replying!
