### ISSUE TITLE
visualize result question

### ISSUE THREAD

**Issue by changliucoding** [exiawsh/StreamPETR#57]
Hi! I successfully ran the visualize.py program and got the picture below. I would like to ask how should this picture be viewed? Why does this camara-only algorithm have radar and lidar related data?
Do I need to use the data of fused-radar and lidar, or are they just for viewing pictures?
![123](https://github.com/exiawsh/StreamPETR/assets/133587429/9a84aaf0-58a2-4a10-b7a2-cc7e8b432335)

**Comment by exiawsh** [comment]
@changliucoding The radar and lidar data are just for visulization only

**Comment by changliucoding** [comment]
> 

Many thanks for the reply! I would like to know in this fused_radar and lidar vis_result example, which points are generated by radar and lidar data, and which are generated by streampetr model? How can I tell them?

**Comment by exiawsh** [comment]
@changliucoding  The purple square (pedestrain) and yellow bounding box (car) are generated by the streampetr model. Others are Lidar and radar points.
