### ISSUE TITLE
Memory center

### ISSUE THREAD

**Issue by raozhongyu** [exiawsh/StreamPETR#61]
Thanks for your great job. I'd like to konw what's the memory_cneter in the streampetr_head?

**Comment by exiawsh** [comment]
@raozhongyu The xyz detection results of the past frames.

**Comment by raozhongyu** [comment]
Thanks a lot



发自我的iPhone


------------------ Original ------------------
From: exiawsh ***@***.***&gt;
Date: Wed,Jul 19,2023 3:02 PM
To: exiawsh/StreamPETR ***@***.***&gt;
Cc: raozhongyu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [exiawsh/StreamPETR] Memory center (Issue #61)





 
@raozhongyu The xyz detection results of the past frames.

**Comment by raozhongyu** [comment]
I'd like use the petr or stream petr to transform the one image to BEV space. Could you give me some suggestions and notice? Thanks a lot

**Comment by exiawsh** [comment]
@raozhongyu  You want to adapt streampetr to monocular 3D object detection?

**Comment by raozhongyu** [comment]
Yes, I try to build an end-to-end autonomous driving framework and I want to use the streampetr as the perception part. However, my dataset is based on the monocular. In this way, I'd like to ask for some suggestions.

**Comment by exiawsh** [comment]
@raozhongyu You can use a monocular 3D object detector, e.g. FCOS3D. Because our baseline PETR is a multi-view 3D object detector, some designs are not compatible. You can transform the depth estimation into ego vehicle coordinates and then propagate the temporal information frame-by-frame based on ego pose changes.

**Comment by raozhongyu** [comment]
I get it. Thanks a lot.
