### ISSUE TITLE
confusion about "use_hybrid_tokens=False"  and "TopK_index" in Focal Head?

### ISSUE THREAD

**Issue by Songustc** [exiawsh/StreamPETR#64]
Thanks for your  excellent work! I wonder how "use_hybrid_tokens" affect results and why shape of TopK_indexes is equal to num_tokens?

**Comment by exiawsh** [comment]
@Songustc The performance (mAP and NDS) will drop a little If you set "use_hybrid_tokens" to True.  The focal Head can sample some foreground tokens, which can reduce the computational complexity of cross-attention.

**Comment by Songustc** [comment]
> @Songustc The performance (mAP and NDS) will drop a little If you set "use_hybrid_tokens" to True. The focal Head can sample some foreground tokens, which can reduce the computational complexity of cross-attention. You can refer to my previous paper Focal-PETR, it has similar motivation with PnP-detr

Thanks ! But when shape of Topk_indexes is equal to  num_tokens, it will sample all perspective features of n cameras to cross-attn,  and computational complexity will not be reduced?

**Comment by exiawsh** [comment]
@Songustc You are right. The focal sampling is closed in the open-source version.

**Comment by Songustc** [comment]
> sampling

Thanks for your kind reply!
