### ISSUE TITLE
哪里可以设置number of frames for long-term fusion

### ISSUE THREAD

**Issue by PrymceQ** [exiawsh/StreamPETR#65]
找不到哪里设置number of frames for long-term fusion的帧数的

**Comment by exiawsh** [comment]
@PrymceQ Hi, you can refer to this issue:
https://github.com/exiawsh/StreamPETR/issues/24#issuecomment-1573128569
The training frames are controlled by queue_length when using sliding window training.
If you use stream training, the training frames are controlled by seq_split_num.
The length of the memory queue is controlled by the memory_len and topk_proposals.

**Comment by PrymceQ** [comment]
ok thank you
