### ISSUE TITLE
How to use 「nusc_tracking」 to produce tracking id？

### ISSUE THREAD

**Issue by PrymceQ** [exiawsh/StreamPETR#67]
我将pub_test.py中设置成如下
`def parse_args()
    parser = argparse.ArgumentParser(description="Tracking Evaluation")

    parser.add_argument("--work_dir", help="the dir to save logs and tracking results", default='./')

    parser.add_argument("--checkpoint",help="the dir to checkpoint which the model read from",default='test/stream_petr_vov_flash_800_bs2_seq_24e/results_nusc.json')

    parser.add_argument("--hungarian", action='store_true')

    parser.add_argument("--data_root", default='data/nuscenes', type=str)

    parser.add_argument("--version", type=str, default='v1.0-test')

    parser.add_argument("--max_age", type=int, default=3)

    parser.add_argument("--score_threshold", type=int, default=0.25)
    args = parser.parse_args()

    return args`

但是报错了
![2023-07-28 13-59-15 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/109404970/09068ee2-4153-4ed4-8e4e-6117b242e606)

**Comment by exiawsh** [comment]
@PrymceQ The pub_test.py only supports results on the validation set. If you want to obtain the results on the test set. You should submit the JSON file to the nuScenes online benchmark.

**Comment by PrymceQ** [comment]
我将eval注释掉了，目前解决了问题，生成了tracking-result.json

![2023-07-28 15-59-46 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/109404970/8842a133-80d6-41d7-993f-048cf6016e7d)

![2023-07-28 15-59-34 的屏幕截图](https://github.com/exiawsh/StreamPETR/assets/109404970/884abd1d-55ad-4e29-9fe5-2b17c7791b8a)
