### ISSUE TITLE
Test Model With My Own Test Images

### ISSUE THREAD

**Issue by alijafari79** [exiawsh/StreamPETR#68]
Hi @exiawsh

I'm so glad, I got a chance to get to know with you and this project.

My question is that, how I can use the final trained model to test on my own images gathered from the road ?
I would really be happy to get your impression on this issue to help me on getting along with the project :)

Thanks for your attention, Best Regards.
Ali Jafari

**Comment by exiawsh** [comment]
@alijafari79 That's a complex problem. You can refer to this issue: https://github.com/exiawsh/StreamPETR/issues/16
