### ISSUE TITLE
Error about  training by sliding window

### ISSUE THREAD

**Issue by Jacky-gsq** [exiawsh/StreamPETR#69]
Hi，when I set the `seq_mode = False, ngpu=8, batch_size=4, seq_length=4`, I get the following error:

`assert self.groups_num >= self.global_batch_size`,
and I print the related params:
`self.flag:---[0 0 0 ... 0 0 0]
self.flag:---[0 0 0 ... 0 0 0]
self.group_sizes:---[28130]
self.group_sizes:---[28130]
self.groups_num:---1
self.groups_num:---1
self.global_batch_size:---8
self.global_batch_size:---8
`
Do i need to set other params for sliding window training？

**Comment by exiawsh** [comment]
@Jacky-gsq Hi, thanks for the attention. You should change the shuffler_sampler=dict(type='InfiniteGroupEachSampleInBatchSampler'), to
shuffler_sampler=dict(type='DistributedGroupSampler'),

**Comment by Jacky-gsq** [comment]
Thanks a lot！
