### ISSUE TITLE
Question about DN loss

### ISSUE THREAD

**Issue by toyot-li** [exiawsh/StreamPETR#70]
@exiawsh @yingfei1016 Hi, thanks for your great work!

When I delve into the DN details, I am confused about this coefficient

https://github.com/exiawsh/StreamPETR/blob/908c1e42457f75c4e024b8d083d97e3ce656102e/projects/mmdet3d_plugin/models/dense_heads/petr_head_dn.py#L738

It looks like Taylor's Expansion of some circular functions, but I cannot understand its exact meaning. Could you please explain a bit? Thanks.

**Comment by yingfei1016** [comment]
The proportion of positive samples is the volume of the sphere/ the volume of the cube.

sphere: 4/3 * pi * self.split * self.split * self.split
cube：8 

So the  positive rate is 1/6 * pi * self.split * self.split * self.split

**Comment by exiawsh** [comment]
@zen-d Hi, we haven't implement this for fair comparison. We just simplify the cls_avg_factor for convenience. You can try your own idea.
