### ISSUE TITLE
problem of "evaluate the tracking model "

### ISSUE THREAD

**Issue by hjfenghj** [exiawsh/StreamPETR#72]
first I evaluate the detection model and get the result named "result_nucs.josn" on the flod named test.Then I evaluate the tracking model.
but I get the error "ValueError: Length of names must match number of levels in MultiIndex.
"
![1](https://github.com/exiawsh/StreamPETR/assets/72334253/383b5da9-4eb3-452e-9612-6743789c55bc)
![2](https://github.com/exiawsh/StreamPETR/assets/72334253/7cc34454-c308-4c3c-b731-85a0526a5196)

**Comment by exiawsh** [comment]
@hjfenghj Hi, which dataset version have you used for "result_nucs.json" ? It seems that you obtained the json file using v1.0-trainval, while you evaluate the results using v1.0-mini. You should modify the version.

**Comment by hjfenghj** [comment]
Thanks your reply so mush.But I obtained the json file using V1.0-mini,while I evaluate the results using V1.0-mini.Would you please tell me what else could be wrong?

**Comment by exiawsh** [comment]
@hjfenghj  Would you please provide your pandas version? My version is 1.5.0.

**Comment by exiawsh** [comment]
@hjfenghj Hi, have you solved the issue?

**Comment by shadinaguib** [comment]
Hey, I'm having the same issue while testing on v1.0-mini. I tried changing pandas version to 1.5.0 but that didn't change anything.

**Comment by hjfenghj** [comment]
> 

yes,I have change the version of pandas,but that didn't change anything

**Comment by exiawsh** [comment]
@hjfenghj @shadinaguib Hi, it's my fault. You can refer to this issue: https://github.com/xingyizhou/CenterTrack/issues/171#issuecomment-755255922
reinstall mometrics<=1.1.3

**Comment by hjfenghj** [comment]
> @hjfenghj @shadinaguib Hi, it's my fault. You can refer to this issue: [xingyizhou/CenterTrack#171 (comment)](https://github.com/xingyizhou/CenterTrack/issues/171#issuecomment-755255922) reinstall mometrics<=1.1.3

think you very much.it works correctly when I reinstall  motmetrics-1.1.3
