### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by HMPgit** [exiawsh/StreamPETR#73]
Could you please provide the docker?

I tried your setup and faced the following issue. Trying "pip install -e ."

![image](https://github.com/exiawsh/StreamPETR/assets/50717775/be8ea750-6cf4-4d1d-88b5-0705dd577ee5)

**Comment by exiawsh** [comment]
@HMPgit Sorry, we don't have that plan now. We don't have the bandwidth to verify it.

**Comment by yingfei1016** [comment]
You can try this code. https://github.com/hakanardo/StreamPETR/tree/hakan/.devcontainer

**Comment by HMPgit** [comment]
![image](https://github.com/exiawsh/StreamPETR/assets/50717775/2b414b5e-9857-42c0-b9de-2cb476872470)

Do I need line 26 and after in your docker file @yingfei1016 

![image](https://github.com/exiawsh/StreamPETR/assets/50717775/bc7c4332-0e1b-460c-96fd-2b22f4889de7)
