### ISSUE TITLE
Some Questions about the motion normalization layer

### ISSUE THREAD

**Issue by Han-lim** [exiawsh/StreamPETR#76]
Thank you for your great work!

I'm wondering the inputs of MLN.

According to your paper, MLN receives three types of input (time, pos, velo).

1) Does 'Time' represent the timestamp of currently processed frame?

2) Also, do 'Pos' and 'Velo' represent the ego-car's position and velocity, respectively?

**Comment by exiawsh** [comment]
Hi, 
1. the time represents the relative time between two frames.
2. Pos represents the relative pose change of the ego-car. And velocity is the velocity predictions of other cars (corresponding to queries).

**Comment by Han-lim** [comment]
Thank you so much for your reply!
