### ISSUE TITLE
Final results' json file

### ISSUE THREAD

**Issue by apourghani** [exiawsh/StreamPETR#77]
@exiawsh
Hi, Thanks for your great and inspiring work!
We need the final output results (json file) of the model, but unfortunately we don't have enough resources to run the model and extract results for our bachelor project.
We will be very thankful if you provide the output results(json file preferred, also outputs of the final weights (ViT-Large-900q)) of the whole NuScenes dataset (we have the results of the mini version of the dataset).
Thank you,
Aliasghar Pourghani,
Student of Sharif University of Technology.

**Comment by exiawsh** [comment]
Hi, You need the json file on val set or test set? You can download the json file on test set here https://github.com/exiawsh/storage/releases/download/v1.0/StreamPETR_vitl_log.json

**Comment by exiawsh** [comment]
@apourghani  Hi, would you please provide your email? We will send it to your email. And you want to obtain the results on test set, right?

**Comment by apourghani** [comment]
> @apourghani Hi, would you please provide your email? We will send it to your email. And you want to obtain the results on test set, right?

Thank you for your kind attention, I suppose we weren't very clear about our request!
We want the 3D boxes output, in json format, something like the file attached below.
Again, Thank you a lot for your answer.
Here's my email:   apourghani@gmail.com
[results_nusc.zip](https://github.com/exiawsh/StreamPETR/files/12329827/results_nusc.zip)
