### ISSUE TITLE
Question about preparation of my own dataset

### ISSUE THREAD

**Issue by BadNaive** [exiawsh/StreamPETR#79]
Hi @exiawsh 
Thanks for your inspiring great work! 
I have a simple question on the preparation of my own dataset:
If I want to train StreamPETR on my own dataset, do I need to make sure that the time interval of adjacent two frames is 0.5s?

Thank you!

**Comment by exiawsh** [comment]
Hi,
You can change the interval. But make sure using the same intervals during training and testing.

**Comment by BadNaive** [comment]
> 
Thans for your answer!
If the time interval of every two adjacent frames are not equal, such as 0.4s between frame 1 and frame 2, but 0.7s between frame 2 and frame 3, does it matter? Thanks again!

**Comment by exiawsh** [comment]
This is compatible.

**Comment by BadNaive** [comment]
Got it!
Many thanks for your rapidly reply!
