### ISSUE TITLE
Reproduced result of "stream_petr_r50_flash_704_bs2_seq_24e" setting

### ISSUE THREAD

**Issue by spa-yhson** [exiawsh/StreamPETR#82]
Hello,

I have trained the model using the `stream_petr_r50_flash_704_bs2_seq_24e` config file on two RTX 3090 GPUs with a batch size of 8. Upon conducting inference, the obtained results are as follows:

```
mAP: 0.1884                                                                                 
mATE: 0.8913
mASE: 0.3045
mAOE: 1.0583
mAVE: 1.1630
mAAE: 0.4159
NDS: 0.2330
Eval time: 162.1s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.395	0.618	0.167	0.611	1.689	0.451
truck	0.115	0.891	0.259	0.960	1.178	0.362
bus	0.067	1.028	0.253	0.448	2.833	0.658
trailer	0.009	1.254	0.240	1.467	0.702	0.195
construction_vehicle	0.007	1.225	0.574	1.508	0.131	0.410
pedestrian	0.277	0.863	0.294	1.359	0.811	0.722
motorcycle	0.159	0.841	0.310	1.345	1.458	0.417
bicycle	0.181	0.728	0.304	1.511	0.503	0.112
traffic_cone	0.370	0.666	0.347	nan	nan	nan
barrier	0.303	0.799	0.297	0.316	nan	nan
```

I am inquiring whether these results are valid and reproduced outcomes. If anyone else has previously trained the same model, I kindly request sharing the outcomes. 

I express my gratitude for your assistance.

**Comment by exiawsh** [comment]
@spa-yhson You can send me your training log to wangshihao@bit.edu.cn

**Comment by exiawsh** [comment]
@spa-yhson It seems that there is something wrong with the max iterations.  The max_iters should be 42192 in your settings. You may modify the num_gpus from 8 to 2.
