### ISSUE TITLE
Output json file on validation set

### ISSUE THREAD

**Issue by apourghani** [exiawsh/StreamPETR#83]
@exiawsh
Hi, Thanks for your great and inspiring work!
We need the final output results (json file) of the model, but unfortunately we don't have enough resources to run the model and extract results for our bachelor project.
It will be useful for us if you provide the output results(boxes json file, also outputs of the weights version v2-99-900q with FCOS3D weights) of the validation part of the NuScenes dataset (we have the results of the mini version of the dataset).
Here is my email: apourghani@gmail.com
Regards,
Aliasghar Pourghani,
Student of Sharif University of Technology.

**Comment by exiawsh** [comment]
@apourghani We provided the weights of v2-99-900q here: https://github.com/exiawsh/storage/releases/download/v1.0/stream_petr_vov_flash_800_bs2_seq_24e.pth
You can download it and get the final results using the command in: https://github.com/exiawsh/StreamPETR/blob/main/docs/training_inference.md

**Comment by apourghani** [comment]
Hello again,
Thanks for your attention. we are working on  a server, with a good CPU and RAM, but we don't have access to GPU.
My question is that can we run inference without a GPU? or it is impossible?!
(I know it is a little bit odd to run such models without GPU but we recently have lost our GPU!)
Thank you.

**Comment by exiawsh** [comment]
@apourghani The model should be tested on GPU. You can try google colab.
