### ISSUE TITLE
How to understand the role of "centers2d_offset" and why it is not involved in box decoding?

### ISSUE THREAD

**Issue by hopef** [exiawsh/StreamPETR#86]
Thanks for your excellent work.

About the yoloxhead, is [centers2d_offset](https://github.com/exiawsh/StreamPETR/blob/a732df7aa3d62f5563f07269002a7f3bba16f7af/projects/mmdet3d_plugin/models/dense_heads/yolox_head.py#L363C15-L363C15) just for auxiliary supervision?

```Python
loss_centers2d = self.loss_centers2d(
            flatten_centers2d_offset.view(-1, 2)[pos_masks],
            centers2d_target) / num_total_samples
```

**Comment by exiawsh** [comment]
@hopef Hi, you are right. The centers2d_offset is just for auxiliary supervision. You can delete it if you want to adjust your own dataset.

**Comment by hopef** [comment]
Thank you very much!!!
