### ISSUE TITLE
Running on HPC

### ISSUE THREAD

**Issue by HMPgit** [exiawsh/StreamPETR#87]
I was able to create a Docker using 'FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8' and run it on my local laptop. 

However, I now wish to run it on an HPC with A100 GPUs. To create a Docker on the HPC, I first need to obtain an NVIDIA container image for PyTorch, such as 'FROM nvcr.io/nvidia/pytorch:21.03-py3'. 

However, when using this image, I was unable to match other libraries, such as mmcv-full and mmdet3d. Although I can build and run the Docker, the code fails due to library mismatches. 

I am wondering if anyone has successfully run this on an HPC and would be willing to share their Dockerfile. 

Thank you.

**Comment by exiawsh** [comment]
@HMPgit Hi, you can try the Dockerfile installation from the official mmdetection3d document. 
https://mmdetection3d.readthedocs.io/en/latest/get_started.html
# build an image with PyTorch 1.9, CUDA 11.1
# If you prefer other versions, just modified the Dockerfile
docker build -t mmdetection3d docker/

Run it with:

docker run --gpus all --shm-size=8g -it -v {DATA_DIR}:/mmdetection3d/data mmdetection3d
