### ISSUE TITLE
Question about IterBasedRunner and InfiniteGroupEachSampleInBatchSampler with streaming mode

### ISSUE THREAD

**Issue by MMz000** [exiawsh/StreamPETR#92]
Thanks for your excellent work and code! The attached image showcases the input parameters for the dataloader in two different training modes when `dist=False`. I have observed that in the streaming mode, the `runner type` in the config consistently remains as `IterBasedRunner`. My question is, is it necessary to use `IterBasedRunner` when using `InfiniteGroupEachSampleInBatchSampler`? If so, could you please explain the reason?

Additionally, I am curious about the reason behind setting the `batch_size` parameter to 1 in the streaming mode.

![image](https://github.com/exiawsh/StreamPETR/assets/55490761/2559e05e-f1db-451a-ad2d-8852e6a2cb75)

**Comment by exiawsh** [comment]
It is necessary to use IterBasedRunner when using InfiniteGroupEachSampleInBatchSampler.
Because we need to process data samples sequentially (Ensure that the data processed by each GPU is video from the same scene). The length of the video of different scenes is not the same, and it cannot be guaranteed that the length of each epoch is fixed.
The batch_size can be changed in streaming mode.

**Comment by MMz000** [comment]
Thank you for your reply! Regarding the `batch_size` issue I mentioned, I was referring to the part in the code at https://github.com/exiawsh/StreamPETR/blob/a732df7aa3d62f5563f07269002a7f3bba16f7af/projects/mmdet3d_plugin/datasets/builder.py#L90-L116 where batch_size is directly set to 1 and then passed to the dataloader.

After looking into PyTorch's DataLoader, I found that the value of `batch_size` in the code above can be chosen arbitrarily because in the `__init__` of `DataLoader`, if `batch_sampler` is not None, then `batch_size` will be set to `None`

> https://github.com/pytorch/pytorch/blob/d69c22dd61a2f006dcfe1e3ea8468a3ecaf931aa/torch/utils/data/dataloader.py#L248-L255

```
        if batch_sampler is not None:
            # auto_collation with custom batch_sampler
            if batch_size != 1 or shuffle or sampler is not None or drop_last:
                raise ValueError('batch_sampler option is mutually exclusive '
                                 'with batch_size, shuffle, sampler, and '
                                 'drop_last')
            batch_size = None
            drop_last = False
```
