### ISSUE TITLE
why `Move box to ego vehicle coord system` when visualization of results in `visual_nuscenes.py`

### ISSUE THREAD

**Issue by furyNerd** [exiawsh/StreamPETR#95]
hi, may i have some help to undstand why `Move box to ego vehicle coord system` when visualization of results in `visual_nuscenes.py`, as follows:

https://github.com/exiawsh/StreamPETR/blob/a732df7aa3d62f5563f07269002a7f3bba16f7af/tools/visual_nuscenes.py#L329-L337

it looks like inherit from bevformer:
https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/tools/analysis_tools/visual.py#L186-L194

but i did not find any clue...

maybe it's misunderstand but according to me the `box` extracted from results is already w.r.t. `ego vehicle coord system`, why here do the frame-transform again? which coord-system the `box` in results extactly belongs to?

thanks very much

**Comment by exiawsh** [comment]
Because the bounding boxes in the json files are in the world coordinate.

**Comment by furyNerd** [comment]
> Because the bounding boxes in the json files are in the world coordinate.

thanks for explanation, for starters like me, who may want refer to the clues, i found the followings:

https://github.com/open-mmlab/mmdetection3d/blob/v1.2.0/mmdet3d/evaluation/metrics/nuscenes_metric.py#L451
