### ISSUE TITLE
About GPU memory.

### ISSUE THREAD

**Issue by xu19971109** [exiawsh/StreamPETR#96]
Hi~ When I trained the model, I found the memory in per GPU is not equal, and a warning `Rank X using best-guess GPU X to performe barrier as devices used by this process are currently unknown.`

I searched the warning, it seems torch 1.9 cause the problem. Did you have the problem of  GPU memory when you trained the model? How was it solved? 

![Knujfgyevm](https://github.com/exiawsh/StreamPETR/assets/50237122/dbd01120-e601-43e9-bb66-04ef1370d6b4)

**Comment by exiawsh** [comment]
@xu19971109 Hi the unequal memory consumption may be caused by the use of checkpoints. And the warning you mentioned will not affect the results. I remember that the warning may be caused by the way of pre-train initialization (pretrained='torchvision://resnet50', using the link to initialize, replacing it with disk pre-train weights may solve the problem).

**Comment by xu19971109** [comment]
@exiawsh Hi~!
I tried to do below, 
> 1. Modify the pretrained config.
>  2. Upgrade torch to version 1.10.0.

 But neither of them worked.
I tried to train on another server. There is still this problem.

![181baa38-57f6-413d-a89e-a4056c4d74f9](https://github.com/exiawsh/StreamPETR/assets/50237122/4552a879-cce8-4c5c-82a2-4f516db153b1)

**Comment by exiawsh** [comment]
@xu19971109 The usage of checkpoint may be caused the unequal memory consumption, which is controlled by with_cp in the config.

**Comment by xu19971109** [comment]
@exiawsh Hi~ I changed with_cp  to False. It worked! If I close with_cp, does it impact the results of the model?

**Comment by exiawsh** [comment]
@xu19971109  It will not affect the results. The unequal memory consumption is normal and I advise you to use it, which can save the GPU memory largely.

**Comment by xu19971109** [comment]
@exiawsh Thank you very much! I have no more question.
