### ISSUE TITLE
The log of ViT-L on test set

### ISSUE THREAD

**Issue by dk-liang** [exiawsh/StreamPETR#98]
Could you please provide the log trained on trainval set of ViT-L?

**Comment by yingfei1016** [comment]
You can find here https://github.com/exiawsh/StreamPETR/issues/33.

**Comment by dk-liang** [comment]
Thanks, how to set the "ida_aug_conf" on ViT-L?

**Comment by yingfei1016** [comment]
only change the final_dim

**Comment by dk-liang** [comment]
Is this right?

ida_aug_conf = {
"resize_lim": (0.94, 1.25),
"final_dim": (800, 1600),
"bot_pct_lim": (0.0, 0.0),
"rot_lim": (0.0, 0.0),
"H": 900,
"W": 1600,
"rand_flip": True,
}

**Comment by yingfei1016** [comment]
yes

**Comment by dk-liang** [comment]
Hello,
I would like to know which **resize_lim** you used for ViT-L on the test set for ViT-L on the test set:

ida_aug_conf = {
**"resize_lim": (0.94, 1.25),**
"final_dim": (800, 1600),
"bot_pct_lim": (0.0, 0.0),
"rot_lim": (0.0, 0.0),
"H": 900,
"W": 1600,
"rand_flip": True,
}


or 

ida_aug_conf = {
**"resize_lim": (1.175, 1.25),**
"final_dim": (800, 1600),
"bot_pct_lim": (0.0, 0.0),
"rot_lim": (0.0, 0.0),
"H": 900,
"W": 1600,
"rand_flip": True,
}

**Comment by yingfei1016** [comment]
(0.94, 1.25)

**Comment by dk-liang** [comment]
Thank you for your prompt reply
